/**
 * THE TYPE LAYER — the half of §76 constraint 2 that the compiler enforces.
 *
 * `DECISIONS-FOR-URI.md` §76, constraint 2, verbatim:
 *
 *   > *"Derived values render as READ-ONLY and recompute live. A panel that let you type
 *   > `SUDDEN_DEATH_MS` would un-fix the exact bug he found by playing."*
 *
 * Rendering read-only is a UI decision, and a UI decision can be forgotten by the next
 * screen that touches the store. **A type cannot.** This file makes `{ SUDDEN_DEATH_MS: 5 }`
 * fail `tsc`, so the refusal survives a rewrite of the panel.
 *
 * `tools/tmp/tun_gate.mjs` proves it by running a **real `tsc`** over a known-bad fixture and
 * requiring a non-zero exit — `CLAUDE.md` #6: a guard that has not been shown to FAIL on the
 * bug it guards against is not a guard, and a type-level assertion is the easiest kind to
 * write vacuously (`Expect<Equal<…>>` helpers that pass on `any` are a genre).
 *
 * ── ⚠️ WHAT THIS FILE DOES **NOT** CATCH, STATED PLAINLY ───────────────────
 *
 * A typo in an AUTHORED key — `{ PLAYER_SPEEED: 0.09 }` — **compiles.** `OverrideSet` carries
 * an index signature because it has to: ~185 of the ~209 registry keys are per-character and
 * are generated by walking the roster (`tuningRegistry.ts:registerCharacterFields`), which is their
 * single source. A static union beside them would be **the second place** §76 constraint 1
 * forbids, and it would agree on the day it was written and rot from the next roster edit on.
 *
 * That hole is closed at RUN TIME instead, in two places, and neither is optional:
 *   * `validate.ts:parseSet` refuses an unknown key before anything is persisted — the panel's
 *     path;
 *   * `tuningRegistry.ts:sealRegistry` THROWS on an installed override that matched no constant —
 *     the `FA_TUNING` / host-injection path, i.e. the one the gate battery runs under.
 *
 * ── ⚠️ AND A TEMPLATE-LITERAL KEY IS NOT A CHECK EITHER ────────────────────
 *
 * `` `char.${string}` `` accepts `char.nosuchcharacter.Nope.damage`. It is documentation with
 * a compiler behind it, not validation: it stops `charr.` and `char_`, and nothing more.
 */

import type { DerivedScheduleKey, DerivedFogKey, DerivedFnKey } from '../rules.ts';

/**
 * Every key an override may **never** name.
 *
 * ⚠️ **DERIVED FROM `rules.ts`, NEVER TYPED HERE.** Each member is `keyof typeof <block>` for
 * a real `deriveds()` / `deriveFns()` call, so adding a derived value in `rules.ts` extends
 * this union with no edit to this file — and *deleting* one removes it, rather than leaving a
 * stale name that refuses a key nobody has any more. Listing them by hand would be the second
 * place again, on the exact rule this file exists to enforce.
 */
export type DerivedKey = DerivedScheduleKey | DerivedFogKey | DerivedFnKey;

/** A per-character registry key. Shape only — see the header for what this cannot check. */
export type CharacterKey = `char.${string}`;

/**
 * A set of overrides, as the panel and `FA_TUNING` hand it over.
 *
 * The intersection is the whole trick: the index signature admits any authored or
 * per-character key with a `number`, and `{ [K in DerivedKey]?: never }` then requires those
 * particular properties to be assignable to `undefined`. `5` is not, so the literal is
 * rejected at the property rather than at the object — which is why the error message names
 * the offending constant instead of pointing at the brace.
 */
export type OverrideSet =
  & { readonly [key: string]: number | undefined }
  & { readonly [K in DerivedKey]?: never };

/**
 * The envelope `validate.ts:exportSet` writes and `store.ts:parseBootstrapPayload` accepts.
 *
 * `tuningHash` is a **STAMP, not an input**: nothing re-derives the set from it and nothing
 * trusts it. It exists so a set sitting in a file can be matched against the
 * `tuningStamp()` recorded in a measurement without re-hashing anything by hand.
 */
export interface TuningEnvelope {
  tuningHash: string;
  savedAt: string;
  overrides: Record<string, number>;
}
