#!/usr/bin/env node
/**
 * FS_SCHED_RING — DOES THE RING ACTUALLY ARRIVE?
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * WHY THIS EXISTS
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Uri played the deployed build and reported:
 *
 *   > *"It start decreasing my HP before it reaches me… it does seem like sudden death,
 *   > it's also written and the entire screen becomes purple. **It happens before the fog
 *   > reaches the center.**"*
 *
 * That defect was **already written down in this repo and never connected to play**.
 * `rules.ts:minSafeRadiusFor` carried the comment *"at the shipped constants this
 * function's result is never reached — `SUDDEN_DEATH_MS` collapses the ring 9.6-11.8 s
 * before the schedule would arrive there"*, and `docs/STATE.md` correction 10 said the same.
 * A documented dead branch was a player-visible bug.
 *
 * This tool measures the thing that comment was about, **on real matches**, so it cannot go
 * back to being a comment: the ring arrives at `minSafeRadiusFor(N)`, the collapse is after
 * the arrival and not before, and nothing burns during the hold.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * THE KNOWN-BAD, AND WHY THERE ARE TWO OF THEM
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * A guard that has not been shown to FAIL on the bug it guards against is not a guard, and
 * a guard can also pass by having nothing left to check. Both are covered:
 *
 *   **KB-1 (ANALYTIC).** The predicates below take a `(playMs, radius)` SERIES, not a match.
 *   KB-1 feeds them a series generated by the schedule `git show 71f670b:src/game/sim.ts`
 *   actually shipped — `max(minSafeRadiusFor(N), 1985 * (1 - t / 45_000))` with the 30 s
 *   trigger — and REQUIRES the arrival predicate to fail. ⚠️ Declared limit: this is a
 *   faithful re-implementation of the old expression, not the old sim. It proves the
 *   predicate can say no; it does not prove the old sim behaved this way.
 *
 *   **KB-2 (LIVE SIM).** The same predicate, over a trace from the CURRENT sim truncated at
 *   the OLD 45 s clock. The ring has not arrived by then, so the predicate must fail — on a
 *   real trace, from real `stepMatch` calls. This is what says KB-1 is not testing my own
 *   arithmetic against itself.
 *
 * Every counted set is asserted NON-EMPTY before anything is asserted over it. `[].every()`
 * returns `true`, and that trap has fired three times in three files in this project.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * USAGE
 * ═══════════════════════════════════════════════════════════════════════════
 *
 *   node tools/tmp/fs_sched_ring.mjs                 # the ring: arrival, ordering, hold
 *   node tools/tmp/fs_sched_ring.mjs --balance       # + fog share, resolveTimeout, regen
 *   node tools/tmp/fs_sched_ring.mjs --seeds 24      # more matches for the balance arm
 *   node tools/tmp/fs_sched_ring.mjs --json out.json
 *
 * Exit 1 on any failed row, and on a known-bad that PASSES.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '../..');

// The TS loader every tool here uses. `--experimental-strip-types` is on the node in use;
// if the import throws, that is the message you want, not a silent fallback.
const RULES = await import(`${ROOT}/src/game/rules.ts`);
const SIM = await import(`${ROOT}/src/game/sim.ts`);
const STATE = await import(`${ROOT}/src/game/state.ts`);

const {
  MATCH_DURATION_MS, FOG_HOLD_MS, FOG_CLOSE_MS,
  SUDDEN_DEATH_MS, SUDDEN_DEATH_GRACE_MS, SUDDEN_DEATH_RADIUS, SUDDEN_DEATH_REMAINING_MS,
  suddenDeathActive, minSafeRadiusFor, fogOpeningRadiusFor, fogRadiusAt,
  FOG_DAMAGE, FOG_TICK_MS, PLAYER_SIZE,
} = RULES;
const { createMatch, stepMatch } = SIM;
const { MAX_FIGHTERS } = STATE;

const args = (() => {
  const o = {};
  const a = process.argv.slice(2);
  for (let i = 0; i < a.length; i++) {
    if (!a[i].startsWith('--')) continue;
    const next = a[i + 1];
    if (next === undefined || next.startsWith('--')) o[a[i].slice(2)] = true;
    else { o[a[i].slice(2)] = next; i++; }
  }
  return o;
})();

let failures = 0;
let rows = 0;
const results = [];
function check(name, pass, detail = '') {
  rows++;
  if (!pass) failures++;
  results.push({ name, pass, detail });
  console.log(`  ${pass ? 'ok  ' : 'FAIL'} - ${name}${detail ? `\n         ${detail}` : ''}`);
}

// ─────────────────────────────────────────────────────────────────────────────
// THE ARENA. The opening radius is `rules.ts:fogOpeningRadiusFor` — IMPORTED, not the
// `Math.round(halfDiag / (1 - 6000 / T))` copy that nine other tools carry and that is now
// wrong by 4.2% (it gives 1792 on the 150 s clock against the shipped 1720.47). The whole
// point of this tool is the schedule, so a private copy of the schedule would be the
// instrument measuring itself.
// ─────────────────────────────────────────────────────────────────────────────
const ARENA_PATH = String(args.arena ?? `${ROOT}/tools/arena.gameplay.json`);
if (!existsSync(ARENA_PATH)) { console.error(`no arena dump at ${ARENA_PATH}`); process.exit(1); }
const DUMP = JSON.parse(readFileSync(ARENA_PATH, 'utf8'));
const HALF_DIAG = Math.hypot(DUMP.width / 2, DUMP.height / 2);
const OPENING = fogOpeningRadiusFor(HALF_DIAG);
const ARENA = { ...DUMP, maxSafeRadius: OPENING, build: () => null, update: () => {} };

const DT = Number(args.dt ?? 100);
const SEEDS = Number(args.seeds ?? 8);

console.log('══ fs_sched_ring ══');
console.log(`arena ${DUMP.width}x${DUMP.height} · opening ring ${OPENING.toFixed(4)} wu (half-diagonal ${HALF_DIAG.toFixed(4)})`);
console.log(`clock ${MATCH_DURATION_MS} ms · hold ${FOG_HOLD_MS} · close ${FOG_CLOSE_MS} · SD ${SUDDEN_DEATH_MS} (+${SUDDEN_DEATH_GRACE_MS})`);
console.log(`dumped maxSafeRadius in ${ARENA_PATH.replace(ROOT + '/', '')}: ${DUMP.maxSafeRadius}${DUMP.maxSafeRadius === OPENING ? '' : '  ← STALE, overridden'}`);

// ─────────────────────────────────────────────────────────────────────────────
// SPAWNS — the same even ring `nf_ffa`/`conceal_lab` use, so two instruments do not
// disagree about where a six-way starts. Radius is the dump's own player spawn distance.
// ─────────────────────────────────────────────────────────────────────────────
function spawnRing(n) {
  const cx = ARENA.center.x, cy = ARENA.center.y;
  const r = Math.hypot(ARENA.playerSpawn.x - cx, ARENA.playerSpawn.y - cy);
  const a0 = Math.atan2(ARENA.playerSpawn.y - cy, ARENA.playerSpawn.x - cx);
  return Array.from({ length: n }, (_, i) => {
    const a = a0 + (i * 2 * Math.PI) / n;
    return { x: cx + Math.cos(a) * r, y: cy + Math.sin(a) * r };
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// THE TRACE. One immortal match per seat count: nobody can die, so the whole schedule is
// walked and every phase is observable. Immortality is the point — a real match ends when
// someone dies, which would truncate the very thing being measured.
// ─────────────────────────────────────────────────────────────────────────────
function traceRing(n, { stopAtPlayMs = Infinity } = {}) {
  const spawns = spawnRing(n);
  const state = createMatch(ARENA, spawns.map((s) => ({ characterId: 'hamburger', spawn: s, controller: 'ai' })));
  state.phase = 'playing';
  for (const f of state.fighters) { f.hp = f.maxHp = 1e9; }
  const inputs = new Array(n).fill(null);
  const series = [];
  const cap = Math.ceil((MATCH_DURATION_MS + 2000) / DT);
  for (let i = 0; i < cap && state.phase === 'playing'; i++) {
    stepMatch(state, DT, inputs);
    const playMs = MATCH_DURATION_MS - state.timeRemaining;
    if (playMs > stopAtPlayMs) break;
    series.push({ playMs, radius: state.safeRadius, sudden: suddenDeathActive(state.timeRemaining) });
  }
  return series;
}

/**
 * THE PREDICATES. They take a SERIES so the same code can be pointed at the live sim and at
 * the old schedule — which is what makes the known-bad a known-bad rather than a second
 * implementation congratulating the first.
 *
 * ⚠️ Each returns its counts, and every caller asserts the count is NON-ZERO before
 * asserting anything about it.
 */
function analyse(series, floor) {
  let arrivedAt = null;
  let collapsedAt = null;
  let rose = 0;
  let heldTicks = 0;
  let floorTicks = 0;
  let prev = Infinity;
  for (const s of series) {
    if (s.radius > prev + 1e-9) rose++;
    prev = s.radius;
    if (!s.sudden) {
      if (s.playMs <= FOG_HOLD_MS && s.radius === OPENING) heldTicks++;
      if (s.radius === floor) { floorTicks++; if (arrivedAt === null) arrivedAt = s.playMs; }
    } else if (collapsedAt === null) collapsedAt = s.playMs;
  }
  return { arrivedAt, collapsedAt, rose, heldTicks, floorTicks, ticks: series.length };
}

console.log('\n1. THE RING ARRIVES — at every seat count, on the shipped arena');
{
  const traces = [];
  for (let n = 2; n <= MAX_FIGHTERS; n++) {
    const floor = minSafeRadiusFor(n);
    const a = analyse(traceRing(n), floor);
    traces.push({ n, floor, ...a });
    console.log(`     N=${n} floor ${floor.toFixed(2)} · ${a.ticks} ticks · held ${a.heldTicks} · on floor ${a.floorTicks} `
      + `· arrived ${a.arrivedAt === null ? 'NEVER' : `${(a.arrivedAt / 1000).toFixed(2)}s`} `
      + `· collapse ${a.collapsedAt === null ? 'NEVER' : `${(a.collapsedAt / 1000).toFixed(2)}s`}`);
  }
  // NON-EMPTY FIRST. If the loop produced no traces every `every()` below is vacuously true.
  check('the corpus is non-empty — one immortal match per seat count, all of them stepped',
    traces.length === MAX_FIGHTERS - 1 && traces.every((t) => t.ticks > 100),
    `${traces.length} traces, min ${Math.min(...traces.map((t) => t.ticks))} ticks`);

  check('🚨 THE RING REACHES minSafeRadiusFor(N) AT EVERY N — the defect Uri played into',
    traces.every((t) => t.arrivedAt !== null),
    traces.map((t) => `N=${t.n}:${t.arrivedAt === null ? 'NEVER' : `${(t.arrivedAt / 1000).toFixed(2)}s`}`).join(' '));

  check('…and it arrives at EXACTLY FOG_CLOSE_MS, independent of N and of the arena',
    traces.every((t) => t.arrivedAt === FOG_CLOSE_MS),
    traces.map((t) => `N=${t.n}:${t.arrivedAt}`).join(' '));

  check('2. SUDDEN DEATH IS AFTER THE ARRIVAL, BY EXACTLY SUDDEN_DEATH_GRACE_MS',
    traces.every((t) => t.collapsedAt !== null && t.collapsedAt - t.arrivedAt === SUDDEN_DEATH_GRACE_MS),
    traces.map((t) => `N=${t.n}:+${((t.collapsedAt - t.arrivedAt) / 1000).toFixed(2)}s`).join(' '));

  check('3. THE PLAYER STANDS ON THE FINAL CIRCLE FOR THE WHOLE GRACE PERIOD',
    traces.every((t) => t.floorTicks === SUDDEN_DEATH_GRACE_MS / DT),
    traces.map((t) => `N=${t.n}:${t.floorTicks} ticks`).join(' '));

  check('4. THE HOLD IS REACHABLE AND THE RING DOES NOT MOVE INSIDE IT',
    traces.every((t) => t.heldTicks === FOG_HOLD_MS / DT),
    traces.map((t) => `N=${t.n}:${t.heldTicks}/${FOG_HOLD_MS / DT}`).join(' '));

  check('5. MONOTONE NON-INCREASING over the whole match, at every N',
    traces.every((t) => t.rose === 0),
    traces.map((t) => `N=${t.n}:${t.rose}`).join(' '));

  // ── KNOWN-BAD 1: THE OLD SCHEDULE, ANALYTIC ──────────────────────────────
  {
    const OLD_T = 45_000, OLD_SD = 30_000, OLD_R0 = 1985;
    const oldSeries = (n) => {
      const floor = minSafeRadiusFor(n);
      const out = [];
      for (let t = DT; t <= OLD_T; t += DT) {
        const sudden = OLD_T - t <= OLD_T - OLD_SD;
        out.push({ playMs: t, radius: sudden ? SUDDEN_DEATH_RADIUS : Math.max(floor, OLD_R0 * (1 - t / OLD_T)), sudden });
      }
      return out;
    };
    const kb = [];
    for (let n = 2; n <= MAX_FIGHTERS; n++) kb.push({ n, ...analyse(oldSeries(n), minSafeRadiusFor(n)) });
    check('KNOWN-BAD 1 (analytic, the schedule 71f670b shipped): the corpus is non-empty',
      kb.length === MAX_FIGHTERS - 1 && kb.every((t) => t.ticks > 100), `${kb.length} series`);
    check('KNOWN-BAD 1: the arrival predicate FAILS on it — the ring reached its floor at NO seat count',
      kb.every((t) => t.arrivedAt === null && t.floorTicks === 0),
      kb.map((t) => `N=${t.n}:${t.arrivedAt === null ? 'never' : t.arrivedAt}`).join(' '));
  }

  // ── KNOWN-BAD 2: THE LIVE SIM, TRUNCATED AT THE OLD CLOCK ────────────────
  {
    const kb2 = [];
    for (let n = 2; n <= MAX_FIGHTERS; n++) kb2.push({ n, ...analyse(traceRing(n, { stopAtPlayMs: 45_000 }), minSafeRadiusFor(n)) });
    check('KNOWN-BAD 2 (LIVE SIM, truncated at the old 45 s clock): the corpus is non-empty',
      kb2.length === MAX_FIGHTERS - 1 && kb2.every((t) => t.ticks > 100),
      `${kb2.length} traces, min ${Math.min(...kb2.map((t) => t.ticks))} ticks`);
    check('KNOWN-BAD 2: the SAME predicate FAILS on a real trace that stops where the old clock did',
      kb2.every((t) => t.arrivedAt === null && t.collapsedAt === null),
      kb2.map((t) => `N=${t.n}:${t.arrivedAt === null ? 'never' : t.arrivedAt}`).join(' '));
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// 6. URI'S SENTENCE, AS A GEOMETRIC FACT: *"it start decreasing my HP before it reaches
// me."* The assertion is the RELATIONSHIP between the two events, not their timestamps:
// a fighter parked at the furthest point the movement clamp allows takes ZERO fog damage
// until the ring's edge has actually swept past it — and the moment it does is
// `fogReachesRadiusAt(dist)`, computed from the schedule, not read off the trace.
// ─────────────────────────────────────────────────────────────────────────────
console.log('\n6. NOBODY BURNS BEFORE THE BOUNDARY ARRIVES (Uri\'s sentence, as a relation)');
{
  // The furthest a fighter's CENTRE can be from the arena centre: `movement.ts` clamps to
  // half a body inside each bound. Derived, never typed.
  const half = PLAYER_SIZE / 2;
  const corner = { x: ARENA.width - half, y: ARENA.height - half };
  const dist = Math.hypot(corner.x - ARENA.center.x, corner.y - ARENA.center.y);
  const arrivesAt = RULES.fogReachesRadiusAt(dist, OPENING, minSafeRadiusFor(2));

  // 🚨 BOTH SEATS ARE `human` WITH NO INPUT, AND THAT IS THE MEASUREMENT, NOT A SHORTCUT.
  // The first draft seated them as `ai` and snapped the corner fighter back to its post at
  // the top of each loop turn — but `stepAI` runs INSIDE `stepMatch`, so it walked the
  // fighter ~12 wu toward the centre BEFORE the fog pass read its position, and the burn
  // landed 640 ms late against a 400 ms window. The row failed for a real reason and the
  // reason was the instrument. A human seat with a hole in the input array reads as frozen
  // NEUTRAL (`sim.ts:NEUTRAL_INPUT`), so nothing moves and the fog pass sees the corner.
  const state = createMatch(ARENA, [
    { characterId: 'hamburger', spawn: { ...corner }, controller: 'human' },
    { characterId: 'hamburger', spawn: { x: ARENA.center.x, y: ARENA.center.y - 300 }, controller: 'human' },
  ]);
  state.phase = 'playing';
  for (const f of state.fighters) { f.hp = f.maxHp = 1e9; }
  let firstBurnAt = null;
  let hp = state.fighters[0].hp;
  let moved = 0;
  const cap = Math.ceil((MATCH_DURATION_MS + 2000) / DT);
  let ticks = 0;
  for (let i = 0; i < cap && state.phase === 'playing'; i++) {
    stepMatch(state, DT, [null, null]);
    ticks++;
    if (state.fighters[0].x !== corner.x || state.fighters[0].y !== corner.y) moved++;
    if (firstBurnAt === null && state.fighters[0].hp < hp) firstBurnAt = MATCH_DURATION_MS - state.timeRemaining;
    hp = state.fighters[0].hp;
  }
  check('the corner fighter never moved — the distance the row is about is the distance the sim saw',
    moved === 0, `${moved} of ${ticks} ticks moved`);
  console.log(`     corner ${corner.x},${corner.y} · dist ${dist.toFixed(2)} wu · edge arrives ${(arrivesAt / 1000).toFixed(2)}s `
    + `· first burn ${firstBurnAt === null ? 'NEVER' : `${(firstBurnAt / 1000).toFixed(2)}s`} · ${ticks} ticks`);
  check('the trace is non-empty and the fighter DID eventually burn (otherwise the row below is vacuous)',
    ticks > 100 && firstBurnAt !== null, `${ticks} ticks, first burn ${firstBurnAt}`);
  check('nothing burns during the HOLD — Uri\'s grace period, at the furthest standable point',
    firstBurnAt !== null && firstBurnAt > FOG_HOLD_MS,
    `first burn ${firstBurnAt} vs hold ${FOG_HOLD_MS}`);
  // Within one fog tick: `applyWorldTick` accumulates `fogTimer` and only bills on the
  // FOG_TICK_MS boundary, so the burn lands in [arrival, arrival + FOG_TICK_MS + DT).
  check('…and the first burn lands within one fog tick of the edge ARRIVING at that point',
    firstBurnAt >= arrivesAt - 1e-9 && firstBurnAt < arrivesAt + FOG_TICK_MS + DT,
    `first burn ${(firstBurnAt / 1000).toFixed(3)}s vs edge arrival ${(arrivesAt / 1000).toFixed(3)}s `
    + `(window ${FOG_TICK_MS + DT} ms)`);
  check('…and the collapse is LATER than that burn, so a corner fighter meets the RING before sudden death',
    firstBurnAt < SUDDEN_DEATH_MS, `${firstBurnAt} vs ${SUDDEN_DEATH_MS}`);
}

// ─────────────────────────────────────────────────────────────────────────────
// 7. THE BALANCE ARM — what a 3.3x clock did to the quantities every published number in
// this project was measured against. NOT a balance verdict: this is the flag, and the peer
// running the full re-measure owns the verdict.
// ─────────────────────────────────────────────────────────────────────────────
if (args.balance) {
  console.log('\n7. WHAT THE LONGER CLOCK DID (flags, not verdicts)');
  const CHARS = RULES.CHARACTER_IDS;
  const HARD_CAP = MATCH_DURATION_MS * 1.6 + 20000;
  const runReal = (n, seed) => {
    const spawns = spawnRing(n);
    const configs = spawns.map((s, i) => ({
      characterId: CHARS[(seed * 7 + i * 3) % CHARS.length],
      spawn: s,
      controller: 'ai',
    }));
    const state = createMatch(ARENA, configs);
    const inputs = new Array(n).fill(null);
    let fog = 0, all = 0, deaths = 0, timedOut = false, suddenDeaths = 0;
    let endedAtPlayMs = null;
    while (state.phase !== 'ended' && state.elapsed < HARD_CAP) {
      const evs = stepMatch(state, DT, inputs);
      for (const ev of evs) {
        if (ev.type === 'hit-landed') {
          all += ev.amount;
          if (ev.source && ev.source.kind === 'fog') fog += ev.amount;
        }
        if (ev.type === 'death') { deaths++; if (suddenDeathActive(state.timeRemaining)) suddenDeaths++; }
      }
      if (state.phase === 'ended' && endedAtPlayMs === null) endedAtPlayMs = MATCH_DURATION_MS - state.timeRemaining;
    }
    if (state.phase === 'ended' && state.fighters.every((f) => f.alive)) timedOut = true;
    return { fog, all, deaths, timedOut, suddenDeaths, endedAtPlayMs, phase: state.phase };
  };

  for (let n = 2; n <= MAX_FIGHTERS; n++) {
    let fog = 0, all = 0, timeouts = 0, sd = 0, matches = 0, sumEnd = 0, unresolved = 0;
    for (let s = 0; s < SEEDS; s++) {
      const r = runReal(n, s);
      matches++;
      fog += r.fog; all += r.all;
      if (r.timedOut) timeouts++;
      sd += r.suddenDeaths;
      if (r.endedAtPlayMs !== null) sumEnd += r.endedAtPlayMs; else unresolved++;
      if (r.phase !== 'ended') unresolved++;
    }
    console.log(`     N=${n}  ${matches} matches · fog share ${(100 * fog / (all || 1)).toFixed(1)}% `
      + `· resolveTimeout ${timeouts} · deaths during sudden death ${sd} `
      + `· mean end ${(sumEnd / Math.max(1, matches - unresolved) / 1000).toFixed(1)}s · unresolved ${unresolved}`);
    results.push({ balance: { n, matches, fogShare: fog / (all || 1), timeouts, suddenDeaths: sd, meanEndMs: sumEnd / Math.max(1, matches - unresolved), unresolved } });
  }
  console.log('     ⚠️ fog share was 8.1% at the 45 s clock (`DECISIONS §1`). These are NOT comparable to');
  console.log('        any published roster number: different driver (all-AI), different N, different clock.');
}

if (args.json) {
  writeFileSync(resolve(String(args.json)), JSON.stringify({
    opening: OPENING, halfDiag: HALF_DIAG, dumpedMaxSafeRadius: DUMP.maxSafeRadius,
    clock: MATCH_DURATION_MS, hold: FOG_HOLD_MS, close: FOG_CLOSE_MS,
    suddenDeath: SUDDEN_DEATH_MS, grace: SUDDEN_DEATH_GRACE_MS,
    rows, failures, results,
  }, null, 2));
}

console.log(`\n${rows - failures} passed, ${failures} failed`);
process.exit(failures ? 1 : 0);
