#!/usr/bin/env node
/**
 * GREASE PUDDLE RE-KEY — price a candidate before writing it.
 *
 * ── Why ──────────────────────────────────────────────────────────────────────
 * `tools/tmp/valuescan.mjs --mode dl` measured 11 characters x 18 stations. 187 of
 * 198 clear the >=0.10 figure/ground standard (mean +0.27) and the failures are not
 * spread out — they pile onto ONE station:
 *
 *     grease_in   mean dL 0.082,   9 of 11 characters below 0.10
 *
 * i.e. one bright disc costs nine characters their worst station. That is an ARENA
 * fact wearing a character costume (`valuescan.mjs`'s `dlBelow10` gate says so out
 * loud), so it is fixed here once instead of eleven times in `src/characters/`.
 *
 * ⚠️ THE LEVER IS VALUE, NOT SATURATION. `docs/LESSONS.md` §8, falsified four times
 * on this project: the arena measures mean saturation 0.4272 against a reference
 * 0.493 and the cast is already 1.8x more saturated than its environment (0.765 vs
 * 0.425). There is nothing here to desaturate. So every candidate below moves L in
 * HSL and holds H and S, and this tool REPORTS the puddle's delivered saturation next
 * to its luma so a candidate that quietly desaturates cannot pass unnoticed.
 *
 * ⚠️ AND IT MUST STILL READ AS A HAZARD. `PUDDLE_SLOW_FACTOR` is 0.45 and terrain slow
 * is 14.6-17.2% of play; a puddle that has dissolved into the tile is a mechanic the
 * player cannot see. So `dPuddleTile` — the puddle's own delivered luma against the
 * tile immediately outside it — is reported for every candidate, and a candidate that
 * wins on `dL` by erasing the puddle loses on that column. Both numbers, every row.
 *
 * ── How ──────────────────────────────────────────────────────────────────────
 * One page load per character at `grease_in`, sim frozen, then N candidates applied
 * live to the disc material. Masks come from the DIRECT render (composer bypassed) —
 * `valuescan.mjs` records why: hiding a mesh changes 41,332 post-processed pixels
 * against a 26,173 px subject, so a post-processed matte is 58% halo. Values are read
 * from the SHIPPED post-processed frame, because that is what the player sees.
 *
 * The puddle's own pixels are found by FRONTMOST SURFACE (hide it, diff the direct
 * render), the same attribution `valuescan.mjs` uses per joint — not by projecting a
 * disc, which would need the world-to-screen scale and would silently include the
 * character standing on it.
 *
 *   node tools/tmp/headserve.mjs --worktree -- node tools/tmp/greasekey.mjs --ids hotdog,waterbottle,taco
 *   node tools/tmp/greasekey.mjs --selftest
 */
import { chromium } from 'playwright';
import sharp from 'sharp';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { VL, VL_SRC } from './valuelib.mjs';

const a = process.argv;
const get = (k, d) => (a.includes(k) ? a[a.indexOf(k) + 1] : d);
const has = (k) => a.includes(k);
const BASE = process.env.PREVIEW_BASE ?? process.env.HEADSERVE_URL ?? get('--url', null);
const OUT = get('--out', 'shots/grease');
const IDS = get('--ids', 'hotdog,waterbottle,taco,lollipop').split(',');
const SHOTS = get('--shots', null);

const LAUNCH_ARGS = ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader',
  '--enable-webgl', '--ignore-gpu-blocklist', '--disable-gpu-sandbox'];
const HMR_STUB = `const noop=()=>{};
export const createHotContext=()=>({accept:noop,acceptExports:noop,dispose:noop,prune:noop,
  invalidate:noop,on:noop,off:noop,send:noop,decline:noop,data:{}});
export const injectQuery=(u)=>u; export const updateStyle=noop; export const removeStyle=noop;
export const ErrorOverlay=class{}; export default {};`;

// ─────────────────────────────────────────────────────────────────────────────
// HSL, so candidates are generated by moving ONE axis and holding the other two.
// ─────────────────────────────────────────────────────────────────────────────
export function hexToHsl(hex) {
  const n = parseInt(hex.replace('#', ''), 16);
  const r = ((n >> 16) & 255) / 255, g = ((n >> 8) & 255) / 255, b = (n & 255) / 255;
  const mx = Math.max(r, g, b), mn = Math.min(r, g, b), d = mx - mn;
  const l = (mx + mn) / 2;
  let h = 0, s = 0;
  if (d > 1e-9) {
    s = d / (1 - Math.abs(2 * l - 1));
    if (mx === r) h = 60 * (((g - b) / d) % 6);
    else if (mx === g) h = 60 * ((b - r) / d + 2);
    else h = 60 * ((r - g) / d + 4);
    if (h < 0) h += 360;
  }
  return { h, s, l };
}
export function hslToHex(h, s, l) {
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const hp = ((h % 360) + 360) % 360 / 60;
  const x = c * (1 - Math.abs((hp % 2) - 1));
  let r = 0, g = 0, b = 0;
  if (hp < 1) [r, g, b] = [c, x, 0]; else if (hp < 2) [r, g, b] = [x, c, 0];
  else if (hp < 3) [r, g, b] = [0, c, x]; else if (hp < 4) [r, g, b] = [0, x, c];
  else if (hp < 5) [r, g, b] = [x, 0, c]; else [r, g, b] = [c, 0, x];
  const m = l - c / 2;
  const q = (v) => Math.max(0, Math.min(255, Math.round((v + m) * 255)));
  return '#' + [q(r), q(g), q(b)].map((v) => v.toString(16).padStart(2, '0')).join('');
}

/** `KPAL.grease` as shipped, and the L ladder under it at fixed H and S. */
const BASE_HEX = get('--base', '#B0802C');

function candidates() {
  const { h, s, l } = hexToHsl(BASE_HEX);
  const out = [{ label: `shipped ${BASE_HEX}`, hex: BASE_HEX, opacity: null }];
  for (const dl of [0.05, 0.08, 0.11, 0.14, 0.17, 0.20]) {
    const nl = Math.max(0.05, l - dl);
    out.push({ label: `L ${l.toFixed(3)}->${nl.toFixed(3)}`, hex: hslToHex(h, s, nl), opacity: null });
  }
  // Same value, more chroma — the direction §8 says is available. Reported so the
  // "value is the lever" claim is checked against its own alternative rather than
  // assumed.
  for (const [dl, ns] of [[0.11, Math.min(1, s + 0.12)], [0.14, Math.min(1, s + 0.12)], [0.17, Math.min(1, s + 0.15)]]) {
    out.push({ label: `L -${dl} S +${(ns - s).toFixed(2)}`, hex: hslToHex(h, ns, Math.max(0.05, l - dl)), opacity: null });
  }
  // Opacity: the disc renders at 0.85 over the tile, so 15% of every darkening is
  // thrown away before it reaches the screen. Priced, not assumed.
  for (const op of [0.92, 1.0]) {
    out.push({ label: `L -0.14 opacity ${op}`, hex: hslToHex(h, s, Math.max(0.05, l - 0.14)), opacity: op });
  }
  return out;
}

// ─────────────────────────────────────────────────────────────────────────────
const CAPTURE = (opts) => {
  const stage = window.__stage;
  if (!stage || stage.disposed) return { error: 'no live Stage' };
  const r = stage.renderer, scene = stage.scene, cam = stage.rig && stage.rig.camera;
  const gl = r.getContext();
  const Wp = r.domElement.width, Hp = r.domElement.height;

  const readAll = () => {
    const buf = new Uint8Array(Wp * Hp * 4);
    gl.readPixels(0, 0, Wp, Hp, gl.RGBA, gl.UNSIGNED_BYTE, buf);
    const out = new Uint8Array(Wp * Hp * 4);
    for (let row = 0; row < Hp; row++) out.set(buf.subarray((Hp - 1 - row) * Wp * 4, (Hp - row) * Wp * 4), row * Wp * 4);
    return out;
  };

  // ── find the GREASE puddle, not the water one ────────────────────────────
  // Identified by its sibling: `buildPuddleVisual` names the overlay
  // `puddle_grease_surface__no_outline`, and only the grease branch does.
  let disc = null, surf = null, rim = null, group = null;
  scene.traverse((o) => {
    if (o.name === 'puddle_grease_surface__no_outline') { surf = o; group = o.parent; }
  });
  if (!group) return { error: 'no grease puddle in the scene' };
  for (const kid of group.children) {
    if (kid.name === 'puddle') disc = kid;
    if (kid.name === 'puddle_wet_rim') rim = kid;
  }
  if (!disc) return { error: 'grease puddle group has no `puddle` disc' };

  const casts = [];
  scene.traverse((o) => { if (/^character:/.test(o.name || '')) casts.push(o); });
  const topOf = (o) => { let n = o; while (n.parent && n.parent !== scene) n = n.parent; return n; };

  const savedBg = scene.background, savedShadow = r.shadowMap.enabled;
  const savedAutoClear = r.autoClear, savedAlpha = r.getClearAlpha();
  let hidden = [];
  const hideEnvironment = (keep) => {
    hidden = [];
    for (const kid of scene.children) { if (keep.has(kid)) continue; if (kid.visible) { hidden.push(kid); kid.visible = false; } }
  };
  const restoreEnvironment = () => { for (const k of hidden) k.visible = true; hidden = []; };
  const direct = () => {
    scene.background = null; r.shadowMap.enabled = false; r.autoClear = true; r.setRenderTarget(null);
    r.setClearColor(0x000000, 1); r.clear(true, true, true); r.render(scene, cam);
    return readAll();
  };
  const matteAll = () => {
    scene.background = null; r.shadowMap.enabled = false; r.autoClear = true; r.setRenderTarget(null);
    r.setClearColor(0x000000, 1); r.clear(true, true, true); r.render(scene, cam);
    const A = readAll();
    r.setClearColor(0xffffff, 1); r.clear(true, true, true); r.render(scene, cam);
    const B = readAll();
    const m = new Uint8Array(Wp * Hp);
    for (let i = 0, j = 0; i < A.length; i += 4, j++) {
      const d = Math.max(Math.abs(A[i] - B[i]), Math.abs(A[i + 1] - B[i + 1]), Math.abs(A[i + 2] - B[i + 2]));
      m[j] = d < 32 ? 1 : 0;
    }
    return m;
  };

  const result = { buffer: [Wp, Hp], rows: [] };
  try {
    // ── player matte ───────────────────────────────────────────────────────
    const perCast = [];
    for (const c of casts) {
      hideEnvironment(new Set([topOf(c)]));
      const others = [];
      for (const o of casts) { if (o !== c && topOf(o) === topOf(c) && o.visible) { others.push(o); o.visible = false; } }
      const m = matteAll();
      for (const o of others) o.visible = true;
      restoreEnvironment();
      let n = 0, x0 = 1e9, x1 = -1, y0 = 1e9, y1 = -1;
      for (let j = 0; j < m.length; j++) {
        if (!m[j]) continue;
        n++; const x = j % Wp, y = (j / Wp) | 0;
        if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y;
      }
      perCast.push({ name: c.name, px: n, bbox: n ? [x0, y0, x1 - x0 + 1, y1 - y0 + 1] : null, mask: m });
    }
    const onScreen = perCast.filter((p) => p.px > 0);
    const named = onScreen.filter((p) => p.name === `character:${opts.playerId}`);
    const player = named.length === 1 ? named[0] : onScreen.sort((x, y) => y.px - x.px)[0];
    if (!player) return { error: 'player has zero on-screen pixels' };
    const [bx, by, bw, bh] = player.bbox;
    const pad = Math.max(12, Math.round(0.30 * bh) + 6);
    const cx = Math.max(0, bx - pad), cy = Math.max(0, by - pad);
    const cw = Math.min(Wp - cx, bw + pad * 2), chh = Math.min(Hp - cy, bh + pad * 2);
    const maskCrop = new Uint8Array(cw * chh);
    for (let y = 0; y < chh; y++) for (let x = 0; x < cw; x++) maskCrop[y * cw + x] = player.mask[(cy + y) * Wp + (cx + x)];
    result.crop = [cx, cy, cw, chh];
    result.charHeightPx = bh;

    // ── the puddle's OWN pixels, by frontmost surface ───────────────────────
    const layerPrev = [disc.visible, surf ? surf.visible : null, rim ? rim.visible : null];
    const base = direct();
    disc.visible = false; if (surf) surf.visible = false; if (rim) rim.visible = false;
    const hid = direct();
    disc.visible = layerPrev[0]; if (surf) surf.visible = layerPrev[1]; if (rim) rim.visible = layerPrev[2];
    const pud = new Uint8Array(Wp * Hp);
    let pudN = 0;
    for (let j = 0; j < Wp * Hp; j++) {
      const i4 = j * 4;
      const d = Math.abs(base[i4] - hid[i4]) + Math.abs(base[i4 + 1] - hid[i4 + 1]) + Math.abs(base[i4 + 2] - hid[i4 + 2]);
      if (d > 12 && !player.mask[j]) { pud[j] = 1; pudN++; }
    }
    result.puddlePx = pudN;
    result.puddlePctOfFrame = +((100 * pudN) / (Wp * Hp)).toFixed(2);
    // the TILE just outside the puddle: a 10px ring around the puddle matte,
    // excluding the character and the puddle itself.
    const ring = new Uint8Array(Wp * Hp);
    let ringN = 0;
    for (let y = 0; y < Hp; y++) for (let x = 0; x < Wp; x++) {
      const j = y * Wp + x;
      if (pud[j] || player.mask[j]) continue;
      let near = false;
      for (let dy = -14; dy <= 14 && !near; dy += 2) for (let dx = -14; dx <= 14; dx += 2) {
        const yy = y + dy, xx = x + dx;
        if (yy < 0 || yy >= Hp || xx < 0 || xx >= Wp) continue;
        if (pud[yy * Wp + xx]) { near = true; break; }
      }
      if (near) { ring[j] = 1; ringN++; }
    }
    result.tileRingPx = ringN;

    const stats = (mask, px) => {
      let L = 0, S = 0, n = 0;
      for (let j = 0; j < Wp * Hp; j++) {
        if (!mask[j]) continue;
        const i = j * 4, R = px[i], G = px[i + 1], B = px[i + 2];
        L += window.VL.luma(R, G, B);
        const mx = Math.max(R, G, B), mn = Math.min(R, G, B);
        S += mx === 0 ? 0 : (mx - mn) / mx;
        n++;
      }
      return n ? { luma: +(L / n).toFixed(4), sat: +(S / n).toFixed(4), n } : { luma: null, sat: null, n: 0 };
    };

    const mat = disc.material;
    const hex0 = '#' + mat.color.getHexString();
    const op0 = mat.opacity;
    result.discMaterial = { colour: hex0, opacity: op0, transparent: mat.transparent };

    for (const cand of opts.cands) {
      mat.color.set(cand.hex);
      if (cand.opacity != null) mat.opacity = cand.opacity; else mat.opacity = op0;
      mat.needsUpdate = true;
      stage.render(0); stage.render(0);
      const px = readAll();
      const luma = new Float32Array(cw * chh);
      for (let y = 0; y < chh; y++) for (let x = 0; x < cw; x++) {
        const s = ((cy + y) * Wp + (cx + x)) * 4;
        luma[y * cw + x] = window.VL.luma(px[s], px[s + 1], px[s + 2]);
      }
      const FG = window.VL.figureGround(luma, cw, chh, maskCrop, { ringFrac: 0.30, edgeR: 4 });
      const P = stats(pud, px), T = stats(ring, px);
      result.rows.push({
        label: cand.label, hex: cand.hex, opacity: cand.opacity ?? op0,
        dL: FG.dL, dLedge: FG.dLedge, figureLuma: FG.figureLuma, groundLuma: FG.groundLuma,
        puddleLuma: P.luma, puddleSat: P.sat, tileLuma: T.luma, tileSat: T.sat,
        dPuddleTile: +((P.luma - T.luma)).toFixed(4),
      });
      // ── the picture, wide enough to contain the whole puddle ────────────────
      // Non-negotiable #3: judge rendered pixels. A crop tight to the fighter shows
      // the dL the table already reports and hides the question that decides this —
      // does the disc still read as a spill? So shots are taken on a region sized to
      // the PUDDLE, not to the character.
      if (opts.shots && opts.shots.includes(cand.label)) {
        const SW = Math.min(Wp, 780), SH = Math.min(Hp, 520);
        const sx = Math.max(0, Math.min(Wp - SW, Math.round(bx + bw / 2 - SW / 2)));
        const sy = Math.max(0, Math.min(Hp - SH, Math.round(by + bh / 2 - SH / 2)));
        const rgb = new Uint8Array(SW * SH * 3);
        for (let y = 0; y < SH; y++) for (let x = 0; x < SW; x++) {
          const sI = ((sy + y) * Wp + (sx + x)) * 4, d = (y * SW + x) * 3;
          rgb[d] = px[sI]; rgb[d + 1] = px[sI + 1]; rgb[d + 2] = px[sI + 2];
        }
        let str = '';
        for (let i = 0; i < rgb.length; i += 8192) str += String.fromCharCode.apply(null, rgb.subarray(i, i + 8192));
        (result.pngs ??= {})[cand.label] = { w: SW, h: SH, b64: btoa(str) };
      }
    }
    mat.color.set(hex0); mat.opacity = op0; mat.needsUpdate = true;
  } finally {
    restoreEnvironment();
    scene.background = savedBg; r.shadowMap.enabled = savedShadow;
    r.autoClear = savedAutoClear; r.setClearColor(0x000000, savedAlpha);
    try { stage.render(0); } catch { /* best effort */ }
  }
  return result;
};

// ─────────────────────────────────────────────────────────────────────────────
function selftest() {
  let pass = 0, fail = 0;
  const ck = (n, got, want, eps) => {
    const ok = typeof want === 'number' ? Math.abs(got - want) <= (eps ?? 1e-6) : JSON.stringify(got) === JSON.stringify(want);
    if (ok) { pass++; console.log(`  ✓ ${n.padEnd(56)} ${JSON.stringify(got)}`); }
    else { fail++; console.log(`  ✗ ${n.padEnd(56)} got ${JSON.stringify(got)} want ${JSON.stringify(want)}`); }
  };
  console.log('\nGREASEKEY SELFTEST — the colour maths, against values derived by hand\n');
  // `KPAL.grease` = #B0802C = (176,128,44). max 176 min 44, L = 220/510 = 0.4314,
  // d = 132/255 = 0.5176, S = d/(1-|2L-1|) = 0.5176/0.8627 = 0.6, H = 60*(84/132) = 38.18.
  const h = hexToHsl('#B0802C');
  ck('KPAL.grease hue', +h.h.toFixed(2), 38.18, 0.02);
  ck('KPAL.grease saturation', +h.s.toFixed(4), 0.6000, 1e-3);
  ck('KPAL.grease lightness', +h.l.toFixed(4), 0.4314, 1e-3);
  ck('round trip is exact', hslToHex(h.h, h.s, h.l), '#b0802c');
  // Darkening at fixed H and S must not change either.
  const dk = hexToHsl(hslToHex(h.h, h.s, h.l - 0.14));
  ck('L -0.14 keeps hue', +dk.h.toFixed(1), +h.h.toFixed(1), 0.6);
  ck('L -0.14 keeps HSL saturation', +dk.s.toFixed(3), +h.s.toFixed(3), 0.01);
  ck('L -0.14 lands where asked', +dk.l.toFixed(3), +(h.l - 0.14).toFixed(3), 0.005);
  // ...but HSV saturation, which is what `arena-scan`/`chroma.mjs` report, RISES when
  // you darken at fixed HSL S. Stated because "do not desaturate" is a rule about the
  // reported number, and darkening moves it the SAFE way.
  const hsvS = (hex) => {
    const n = parseInt(hex.slice(1), 16);
    const r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
    const mx = Math.max(r, g, b), mn = Math.min(r, g, b);
    return mx === 0 ? 0 : (mx - mn) / mx;
  };
  ck('HSV sat of shipped grease', +hsvS('#B0802C').toFixed(4), 0.75, 0.01);
  ck('HSV sat AFTER L -0.14', +hsvS(hslToHex(h.h, h.s, h.l - 0.14)).toFixed(4), 0.75, 0.02);
  ck('darkening at fixed HSL-S does not lower HSV-S',
    hsvS(hslToHex(h.h, h.s, h.l - 0.14)) >= hsvS('#B0802C') - 0.02, true);
  // Luma of the authored albedo, so the direction of the change is unambiguous.
  ck('luma(#B0802C)', +VL.luma(176, 128, 44).toFixed(4), 0.5187, 1e-3);
  const d14 = hslToHex(h.h, h.s, h.l - 0.14);
  const n14 = parseInt(d14.slice(1), 16);
  // NOT 0.14. HSL lightness and Rec.709 luma are different quantities, and for a
  // saturated warm the gap is 20%: #B0802C (176,128,44) -> #77561E (119,86,30) is
  // 0.5182 -> 0.3492. Written as 0.140 first, on the assumption that "L -0.14" moves
  // luma by 0.14; the tool disagreed and the tool was right. Recorded because the
  // whole point of this file is that VALUE is the lever, and a lever calibrated in
  // the wrong unit is how a measured change lands 20% off target.
  ck('L -0.14 lowers authored REC709 LUMA by',
    +(VL.luma(176, 128, 44) - VL.luma((n14 >> 16) & 255, (n14 >> 8) & 255, n14 & 255)).toFixed(3), 0.169, 0.003);
  console.log(`\n${pass} passed, ${fail} failed`);
  return fail === 0 ? 0 : 1;
}

// ─────────────────────────────────────────────────────────────────────────────
if (has('--selftest')) process.exit(selftest());
if (!BASE) { console.error('PREVIEW_BASE unset — run under headserve.mjs/with_snapshot.mjs'); process.exit(2); }
await mkdir(OUT, { recursive: true });

const cands = candidates();
console.log(`base ${BASE_HEX}  ->  ${cands.length} candidates`);
const browser = await chromium.launch({ args: LAUNCH_ARGS });
const all = {};
try {
  for (const id of IDS) {
    const page = await browser.newPage({ viewport: { width: 1600, height: 900 }, deviceScaleFactor: 1 });
    await page.addInitScript({ content: VL_SRC });
    await page.route('**/@vite/client*', (r) => r.fulfill({ status: 200, contentType: 'text/javascript', body: HMR_STUB }));
    page.on('pageerror', (e) => console.error('  PAGEERROR', String(e).slice(0, 200)));
    try {
      const url = `${BASE}/?player=${id}&enemy=donut&px=560&py=900&fogRadius=850&simSpeed=0.02&pointerLock=0`;
      await page.goto(url, { waitUntil: 'networkidle', timeout: 120000 });
      await page.waitForFunction('window.__gameReady === true', null, { timeout: 120000 });
      await page.waitForTimeout(900);
      const res = await page.evaluate(CAPTURE, { playerId: id, cands, shots: SHOTS ? SHOTS.split('|') : null });
      if (res.error) { console.error(`✗ ${id}: ${res.error}`); continue; }
      all[id] = res;
      console.log(`\n${id}  disc ${res.discMaterial.colour} @ opacity ${res.discMaterial.opacity}  puddle ${res.puddlePx}px (${res.puddlePctOfFrame}% of frame)  tile ring ${res.tileRingPx}px`);
      console.log('  candidate                 hex       op      dL   dLedge   fig   grnd | puddleL puddleS  tileL  dPud-Tile');
      for (const r of res.rows) {
        console.log(`  ${r.label.padEnd(24)}${r.hex.padEnd(10)}${String(r.opacity).padStart(5)}${String(r.dL).padStart(8)}${String(r.dLedge).padStart(9)}` +
          `${String(r.figureLuma).padStart(7)}${String(r.groundLuma).padStart(7)} | ${String(r.puddleLuma).padStart(7)}${String(r.puddleSat).padStart(8)}${String(r.tileLuma).padStart(7)}${String(r.dPuddleTile).padStart(10)}`);
      }
      if (res.pngs) {
        for (const [k, v] of Object.entries(res.pngs)) {
          await sharp(Buffer.from(v.b64, 'base64'), { raw: { width: v.w, height: v.h, channels: 3 } })
            .png().toFile(join(OUT, `${id}.${k.replace(/[^a-z0-9]+/gi, '_')}.png`));
        }
      }
    } catch (e) { console.error(`✗ ${id}: ${e}`); } finally { await page.close(); }
  }
} finally { await browser.close(); }

const ids = Object.keys(all);
if (ids.length) {
  console.log(`\nMEAN over ${ids.length} characters at grease_in`);
  console.log('candidate                 hex          dL   n>=0.10   groundL  puddleL  puddleS  dPud-Tile');
  for (let i = 0; i < cands.length; i++) {
    const rows = ids.map((id) => all[id].rows[i]).filter(Boolean);
    const m = (f) => rows.reduce((s, r) => s + f(r), 0) / rows.length;
    console.log(`${cands[i].label.padEnd(24)}${cands[i].hex.padEnd(10)}${m((r) => r.dL).toFixed(4).padStart(9)}` +
      `${String(rows.filter((r) => r.dL >= 0.10).length + '/' + rows.length).padStart(9)}` +
      `${m((r) => r.groundLuma).toFixed(4).padStart(10)}${m((r) => r.puddleLuma).toFixed(4).padStart(9)}` +
      `${m((r) => r.puddleSat).toFixed(4).padStart(9)}${m((r) => r.dPuddleTile).toFixed(4).padStart(11)}`);
  }
}
await writeFile(join(OUT, 'greasekey.json'), JSON.stringify({ cands, all }, null, 2));
console.log(`\nwrote ${OUT}/greasekey.json`);
