#!/usr/bin/env node
/**
 * Build `tools/tmp/ic_variants.json` — the candidate arms for the paired plate.
 *
 * ── Why this is generated and not hand-written ──────────────────────────────
 * A geometry variant is real artwork, so it has to be copied into `src/ui/icons/` if it
 * wins. Everything that has gone wrong in this corner of the project has gone wrong at a
 * TRANSCRIPTION — sizes transcribed into the harness, a `twin` field written where the
 * page reads `twinOf`. So the star polygons here come from the same formula
 * `src/ui/icons/svg.ts` exports rather than from a pasted `d` string, and the four boxes
 * come from one `box2()` the way `ui.ts` builds them from one `box()`.
 *
 * The hand-over is still checked by PIXELS, not by this file: `ic_pair.mjs --handover`
 * requires the shipped tile and the winning variant tile to hash identically.
 *
 *   node tools/tmp/ic_mkvariants.mjs
 */
import { writeFileSync } from 'node:fs';

/** ⚠️ The SAME formula as `src/ui/icons/svg.ts:starPath`, and it must stay that way —
 *  the point of generating rather than pasting is that a variant's star and the shipped
 *  star come out of one derivation. If this ever disagrees, `--handover` fails on
 *  pixels, which is the check that matters. */
function starPath(points, rOuter, rInner, cx = 12, cy = 12) {
  const parts = [];
  for (let i = 0; i < points * 2; i++) {
    const r = i % 2 === 0 ? rOuter : rInner;
    const a = (Math.PI * i) / points - Math.PI / 2;
    parts.push(`${(cx + r * Math.cos(a)).toFixed(2)} ${(cy + r * Math.sin(a)).toFixed(2)}`);
  }
  return `M${parts.join('L')}Z`;
}

const P = {
  cream: '#FFF3DE', gold: '#F4A300', goldDark: '#B87400', mustard: '#FFC93C',
  mustardHi: '#FFDD6B', ketchup: '#D62839', lettuce: '#7CB518', white: '#FFFFFF',
};

// ── The box family, with an OVERHANGING FLAT LID ─────────────────────────────
// `ui.ts`'s `box()` draws a TRAPEZOID lid flush with the body: `M3.4 9.4 6.6 5.6 h10.8
// l3.2 3.8 z`. Two things follow at the delivered 11.83px that the 20px harness hid:
//   * a trapezoid over a rectangle is a FACETED SOLID — `boxPineapple` and `boxFire`
//     were each named "a cut gemstone" 3/3 at native size;
//   * the lid is INSIDE the body's silhouette, so the only thing saying "lid" is the
//     0.8px ink seam plus a front/lid value step that for boxBurger is 1.36.
// A lid that is WIDER than the body puts the lid in the SILHOUETTE, which is the one
// channel that survives downscaling (`food.ts`'s own rule), and no wrapped present has
// an overhanging lid. Same three colours, same emblems: colour is held fixed on purpose,
// because `a77ff30` measured three colourways at Δ = 0 of 3 with a clean twin floor.
const box2 = (front, lid, band, emblem = '') => `
<path d="M4.8 10.4h14.4v8.3a1.6 1.6 0 0 1-1.6 1.6H6.4a1.6 1.6 0 0 1-1.6-1.6z" fill="${front}"/>
<path d="M2.2 5.2h19.6v5.2H2.2z" fill="${lid}"/>
<path d="M9.9 8.4h4.2v5.2H9.9z" fill="${band}" stroke-width="1.3"/>
${emblem}`;

/* Moved down and right with the front panel, which is 1.4 units narrower than the old
   one. Nothing else about the mark changes. */
const BURGER_EMBLEM2 = `<path d="M5.8 14.1a2.6 2.6 0 0 1 5.2 0z" fill="#B4622A" stroke-width="1.2"/>
<path d="M5.6 14.1h5.6v1.5H5.6z" fill="${P.lettuce}" stroke-width="1.2"/>
<path d="M5.8 15.7h5.2a2.2 2.2 0 0 1-5.2 0z" fill="#B4622A" stroke-width="1.2"/>`;
const BOW_EMBLEM = `<path d="M12 5.6C9.2 1.6 4.8 2.8 6.2 5.6M12 5.6C14.8 1.6 19.2 2.8 17.8 5.6" fill="${P.mustard}" stroke-width="1.4"/>`;

const V = {
  _: [
    'Variants for the PAIRED plate (tools/tmp/ic_pair.mjs). GENERATED by',
    'tools/tmp/ic_mkvariants.mjs — edit that, not this.',
    '',
    'Arm [A] of every subject is SHIPPED ART: it overrides nothing, so it draws whatever',
    'src/ui/icons/ currently contains. That is what makes `--handover` possible — after a',
    'winner is pasted in, [A] and the winning arm must hash to the same pixels.',
    '',
    '`fills` is a positional substitution into the icon`s own fill= attributes.',
    '`svg` REPLACES the glyph interior, which is real new art and is why the hand-over',
    'check exists at all.',
  ],

  // ── coin — 11.03 px on rgb(253,233,212), ink outline. The primary currency. ──
  // r3: 1/3 with zoom (a bottle cap x1, a snail shell spiral x1), 0/3 without
  // (a tomato x2, an egg x1). Read off the 11x magnification of the delivered plate:
  // at 11 px the glyph is almost entirely OUTLINE. It is three separately ink-stroked
  // shapes — base ellipse, face ellipse, star — inside an 8 px circle, so 1.7 units of
  // ink (0.78 px) is drawn four times over and the gold never becomes a mass. What is
  // left is a squat two-tone oval with a dark bottom rim, which is `cap`'s construction
  // exactly (an ellipse plus a same-shape darker ellipse offset downward) and `egg`'s
  // silhouette approximately.
  // 🔴 VERDICT: [B] WON AND IS NOW SHIPPED. native 0/3 -> 3/3 (Δ +3 of 3), magnified
  // 3/3 -> 3/3, twin floor 0 of 9. [A] is therefore now the SAME ART as [B]; the pair is
  // kept so `--handover coin=B` can prove the paste by pixels, and [C] is kept because it
  // is the arm that separated "the ink budget" from "the tilt" (2/3 native: removing the
  // interior strokes recovers most of it, removing the tilt recovers all of it).
  coin: [
    { id: 'A', note: 'SHIPPED — after this pass, the disc. Before it, a tilted ellipse pair with every element ink-stroked, 0/3 native, "a bottle cap" x3.' },
    {
      id: 'B',
      note: 'DISC + RIM + un-stroked star. Kills the tilt (which is what made it a cap) and every INTERIOR stroke, so the gold is a mass and the star is at full contrast.',
      svg: `
<circle cx="12" cy="12" r="9.5" fill="${P.goldDark}"/>
<circle cx="12" cy="12" r="7.6" fill="${P.gold}" stroke="none"/>
<path d="${starPath(5, 5.8, 2.5, 12, 12)}" fill="${P.cream}" stroke="none"/>`,
    },
    {
      id: 'C',
      note: 'THE TILT KEPT, THE INTERIOR STROKES REMOVED. Isolates the two halves of the diagnosis: if C alone recovers the read, the defect was INK BUDGET; if only B does, it was the tilted silhouette.',
      svg: `
<ellipse cx="12" cy="14.2" rx="9" ry="7" fill="${P.goldDark}"/>
<ellipse cx="12" cy="11.2" rx="9" ry="7" fill="${P.gold}"/>
<path d="${starPath(5, 5.8, 2.5, 12, 11.2)}" fill="${P.cream}" stroke="none"/>`,
    },
  ],

  // ── egg — 22.72 px on WHITE. Named "a gold coin" 3/3 at native size. ────────
  // A CROSS-FAMILY leak: a weapon glyph reading as the primary currency. The cause is
  // construction, not size — the egg is a symmetric ELLIPSE whose right half is filled a
  // whole value darker, and a two-tone vertically split oval is a struck coin seen edge
  // lit. An egg is not an ellipse: it is an ovoid, narrow at the top.
  egg: [
    { id: 'A', note: 'SHIPPED — symmetric ellipse, hard vertical two-tone split.' },
    {
      id: 'B',
      note: 'TRUE OVOID (1:1.44, narrow at the top) + a bottom crescent instead of a vertical half. ⚠️ The outline is RE-STROKED after the shading, which is not decoration: the shipped icon stacks three ink-stroked paths and therefore draws its outline three times, and the first draft of this arm — which drew it once — came back visibly weaker on white. Same ink budget, deliberately.',
      svg: `
<path d="M12 3c3.6 0 6.4 5 6.4 9.8 0 4.6-2.9 8.4-6.4 8.4s-6.4-3.8-6.4-8.4c0-4.8 2.8-9.8 6.4-9.8z" fill="#E4CFA6"/>
<path d="M12 21.2c-3.5 0-6.4-3.8-6.4-8.4 0-.9.1-1.8.3-2.7.6 4.6 3.2 8 6.1 8s5.5-3.4 6.1-8c.2.9.3 1.8.3 2.7 0 4.6-2.9 8.4-6.4 8.4z" fill="#C9AE7C" stroke="none"/>
<path d="M12 3c3.6 0 6.4 5 6.4 9.8 0 4.6-2.9 8.4-6.4 8.4s-6.4-3.8-6.4-8.4c0-4.8 2.8-9.8 6.4-9.8z" fill="none"/>
<path d="M9 9.2a4 4 0 0 1 2.2-2.8" stroke="#FFFBF2" stroke-width="2.2"/>`,
    },
  ],

  // ── medal — 11.19 px on rgb(54,39,73), CREAM outline. ───────────────────────
  // A FULL MUTUAL SWAP with `trophy` at native size: trophy -> medal x3 and
  // medal -> trophy x3. Both are a gold mass with two small appendages sprouting from
  // the top, and at 11 px that is the whole reading. `ui.ts` says this icon "exists
  // purely so the trophy stops meaning two different quantities", so the swap is a
  // failure of its only job.
  medal: [
    { id: 'A', note: 'SHIPPED — two thin splayed ribbons over a gold disc with a mustard hub.' },
    {
      id: 'B',
      note: 'ONE wide ribbon with a V tail, in ketchup. The two splayed strips become one bold mass, the silhouette becomes a band-over-disc pendant, and the RED is a hue the trophy does not own at all.',
      svg: `
<path d="M8.6 1.8h6.8v7.6l-3.4 3-3.4-3z" fill="${P.ketchup}"/>
<circle cx="12" cy="15.6" r="6.3" fill="${P.gold}"/>
<circle cx="12" cy="15.6" r="3.2" fill="${P.mustardHi}" stroke="none"/>`,
    },
  ],

  // ── slow — 13.8 px on the ink fact pill, CREAM outline. ─────────────────────
  // 0/3 at native size, "a bottle cap" x3, and `cap` comes back "a snail shell spiral"
  // x2 — a real mutual swap. The cause is already written down in this repo, one file
  // over: `food.ts`'s `swirl` comment says *"a spiral drawn INSIDE a filled disc is a
  // disc, because the disc is the mass and the spiral is a scratch on it"*, and swirl
  // was redrawn for exactly that. `slow` is the same drawing and was never revisited.
  // ⚠️ A spiral RIBBON was considered and rejected on arithmetic rather than on taste:
  // at 13.8 px one viewBox unit is 0.575 px, so two turns need a gap wider than the
  // stroke and there is no pair of numbers under 24 units that gives one.
  // 🔴 VERDICT: [B] WON AND IS NOW SHIPPED. magnified 1/3 -> 3/3 (Δ +2 of 3), native
  // 0/3 -> 0/3, twin floor 0 of 9. [C] is the control that makes the finding: fattening
  // and darkening the interior spiral to near-ink, with the disc untouched, moved
  // NOTHING at either protocol — the silhouette is the whole lever.
  slow: [
    { id: 'A', note: 'SHIPPED — after this pass, the apex shell. Before it, a gold disc with an interior spiral stroke, 1/3 magnified, "a gold coin" x2.' },
    {
      id: 'B',
      note: 'APEX + a TWO-ELEMENT whorl. The silhouette is broken by a broad shell apex so it is neither a disc nor a lens, and the whorl is one 300° groove at r5 plus a centre dot — the only two marks that resolve at 0.575 px per unit. ⚠️ The first draft used two nested tones for the whorl and rendered as a plain gold teardrop: goldDark on gold under a CREAM outline has no dark edge anywhere, so the whorl was invisible. This groove is near-ink.',
      svg: `
<path d="M13 7.6 21.8 3.6 18.4 13.2z" fill="${P.gold}"/>
<circle cx="10.6" cy="14.2" r="7.8" fill="${P.gold}"/>
<path d="M14.2 18.4a5 5 0 1 1 1-5.6" stroke="#5A3200" stroke-width="2.8" fill="none" stroke-linecap="round"/>
<circle cx="10.6" cy="14.2" r="1.7" fill="#5A3200" stroke="none"/>`,
    },
    {
      id: 'C',
      note: 'WHORL CONTRAST ONLY — the shipped disc, with the interior spiral fattened and darkened to near-ink and no change to the silhouette. Isolates the two halves of the diagnosis: if C alone recovers the read the defect was CONTRAST; if only B does, `food.ts`\'s rule holds and a spiral inside a filled disc is a disc however dark you draw it.',
      svg: `
<circle cx="12" cy="12" r="9.1" fill="${P.gold}"/>
<path d="M12 12a2.9 2.9 0 1 0 2.9 2.9c0-3.4-3.2-5.3-6.3-4.1-3.4 1.3-4.6 5.3-2.6 8.2" stroke="#5A3200" stroke-width="2.8" fill="none" stroke-linecap="round"/>`,
    },
    // ── The HUE arms. 🔴 BOTH LOST, and the hypothesis behind them is FALSIFIED.
    //    [B] fixed the drawing (1/3 -> 3/3 magnified) and left the native read at 0/3,
    //    "a gold coin" x2 + "an egg" x1, from which this file inferred that a warm gold
    //    rounded mass is the currency at 13.8 px. Measured on a second plate, same
    //    silhouette, one variable, twin floor 0 of 9:
    //        A gold (shipped) 3/3 magnified, 1/3 native
    //        D brown          3/3, 1/3   Δ +0
    //        E pink           3/3, 0/3   Δ −1   ← the loudest separation made it WORSE
    //    And with the shell shipped, slow's native misreads moved to burrito / hot dog /
    //    tomato / fish — a different wrong answer every round, which is a LEGIBILITY
    //    failure rather than a collision. Kept so the next pass does not rebuild them.
    {
      id: 'D',
      note: 'SHELL BROWN. `P.woodHi`, the one warm saturated hue in the palette that no currency glyph uses, with a near-ink whorl. Warm chroma is also the budget CLAUDE.md records as SCARCE, so this spends the right one.',
      svg: `
<path d="M13 7.6 21.8 3.6 18.4 13.2z" fill="#B4622A"/>
<circle cx="10.6" cy="14.2" r="7.8" fill="#B4622A"/>
<path d="M14.2 18.4a5 5 0 1 1 1-5.6" stroke="#4A2400" stroke-width="2.8" fill="none" stroke-linecap="round"/>
<circle cx="10.6" cy="14.2" r="1.7" fill="#4A2400" stroke="none"/>`,
    },
    {
      id: 'E',
      note: 'MAXIMUM SEPARATION. `P.candy` pink — no coin, trophy, medal, gear, lock, home, cone or burst is pink, and the ink fact pill it ships on carries nothing pink either. Deliberately not a snail colour: the question this arm asks is whether HUE alone carries the native read once the silhouette is right.',
      svg: `
<path d="M13 7.6 21.8 3.6 18.4 13.2z" fill="#FF6FA5"/>
<circle cx="10.6" cy="14.2" r="7.8" fill="#FF6FA5"/>
<path d="M14.2 18.4a5 5 0 1 1 1-5.6" stroke="#8E2E56" stroke-width="2.8" fill="none" stroke-linecap="round"/>
<circle cx="10.6" cy="14.2" r="1.7" fill="#8E2E56" stroke="none"/>`,
    },
  ],

  // ── the box family — 11.83 px on white, one row of one sheet. ───────────────
  // Colour has been measured and is NOT the lever (a77ff30: three colourways, Δ = 0 of
  // 3, twin floor clean). Both arms below hold the colours FIXED and change only where
  // the lid is.
  // 🔴 [B] LOST — 1/3 -> 1/3 magnified, 0/3 -> 0/3 native, Δ +0 at both. Kept, because
  // three variables (front/lid ratio, clasp dominance, lid silhouette) have now each
  // moved with no effect and the next pass should not spend a fourth on the box's body.
  // [D] was the arm the LOSING round produced — two zoomed judges independently said the
  // box reads as a chest "because unlike the other three nothing sits ON TOP of it" —
  // and 🔴 [D] LOST TOO: 3/3 -> 3/3 magnified, 0/3 -> 0/3 native, Δ +0 at both, twin
  // floor 0 of 9. A judge's stated reason is an observation, not a lever.
  boxBurger: [
    { id: 'A', note: 'SHIPPED — trapezoid lid inside the body silhouette, burger stamped on the FRONT PANEL.' },
    { id: 'B', note: 'REJECTED (Δ +0 both protocols). OVERHANGING FLAT LID, 2.6 units wider than the body each side, trapezoid removed, clasp straddling the seam evenly.', svg: box2(P.gold, P.mustard, P.ketchup, BURGER_EMBLEM2) },
    {
      id: 'D',
      note: 'THE EMBLEM MOVES ONTO THE LID. Shipped geometry, shipped colours, one change: the burger sits ABOVE the lid and breaks the outline, which is what FLAME_EMBLEM, LEAF_EMBLEM and BOW_EMBLEM already do — and those three boxes are the ones that pass. It is the last structural asymmetry in the family.',
      svg: `
<path d="M3.4 9.4h17.2v9.4a1.7 1.7 0 0 1-1.7 1.7H5.1a1.7 1.7 0 0 1-1.7-1.7z" fill="${P.gold}"/>
<path d="M3.4 9.4 6.6 5.6h10.8l3.2 3.8z" fill="${P.mustard}"/>
<path d="M9.8 7h4.4v5.6H9.8z" fill="${P.ketchup}" stroke-width="1.3"/>
<path d="M8.9 3.9a3.1 3.1 0 0 1 6.2 0z" fill="#B4622A" stroke-width="1.2"/>
<path d="M8.7 3.9h6.6v1.1H8.7z" fill="${P.lettuce}" stroke-width="1.2"/>
<path d="M8.9 5h6.2v1.4H8.9z" fill="#B4622A" stroke-width="1.2"/>`,
    },
  ],
  boxRed: [
    { id: 'A', note: 'SHIPPED. 1/3 at native size, "a treasure chest" x2 — the other half of a mutual swap with `chest`.' },
    { id: 'B', note: 'The same overhanging lid, same colourway. Carried on the plate so the geometry is tested on TWO members of a family that shares one function, not on one.', svg: box2(P.ketchup, '#E9536A', P.mustard, BOW_EMBLEM) },
  ],
};

writeFileSync('tools/tmp/ic_variants.json', JSON.stringify(V, null, 2) + '\n');
console.log('wrote tools/tmp/ic_variants.json');
for (const [k, v] of Object.entries(V)) {
  if (k === '_') continue;
  console.log(`  ${k.padEnd(12)} ${v.length} arms: ${v.map((x) => x.id).join(', ')}`);
}
