#!/usr/bin/env node
/**
 * Build `tools/tmp/ic_variants.json` — the candidate arms for the paired plate.
 *
 * ── Why this is generated and not hand-written ──────────────────────────────
 * A geometry variant is real artwork, so it has to be copied into `src/ui/icons/` if it
 * wins. Everything that has gone wrong in this corner of the project has gone wrong at a
 * TRANSCRIPTION — sizes transcribed into the harness, a `twin` field written where the
 * page reads `twinOf`. So the star polygons here come from the same formula
 * `src/ui/icons/svg.ts` exports rather than from a pasted `d` string, and the four boxes
 * come from one `box2()` the way `ui.ts` builds them from one `box()`.
 *
 * The hand-over is still checked by PIXELS, not by this file: `ic_pair.mjs --handover`
 * requires the shipped tile and the winning variant tile to hash identically.
 *
 *   node tools/tmp/ic_mkvariants.mjs
 */
import { writeFileSync } from 'node:fs';

/** ⚠️ The SAME formula as `src/ui/icons/svg.ts:starPath`, and it must stay that way —
 *  the point of generating rather than pasting is that a variant's star and the shipped
 *  star come out of one derivation. If this ever disagrees, `--handover` fails on
 *  pixels, which is the check that matters. */
function starPath(points, rOuter, rInner, cx = 12, cy = 12) {
  const parts = [];
  for (let i = 0; i < points * 2; i++) {
    const r = i % 2 === 0 ? rOuter : rInner;
    const a = (Math.PI * i) / points - Math.PI / 2;
    parts.push(`${(cx + r * Math.cos(a)).toFixed(2)} ${(cy + r * Math.sin(a)).toFixed(2)}`);
  }
  return `M${parts.join('L')}Z`;
}

/** ⚠️ A SUBSET COPY OF `src/ui/icons/svg.ts`'s palette, AND THE SUBSET BIT COST A ROUND.
 *  This started as eight names — the ones the box/coin/slow arms happened to need — so
 *  `${P.water}` in a new arm interpolated to the string `undefined`, SVG rejected
 *  `fill="undefined"` as invalid, and two `swirl` arms rendered as hollow outlines with
 *  no fill at all. Nothing threw: a template literal has no idea a key is missing, the
 *  plate rendered, `ic_pair`'s "variants must differ" control PASSED (an unfilled glyph
 *  differs from a filled one by plenty), and the round would have been judged on artwork
 *  nobody drew. Caught only by reading the PNG — CLAUDE.md #3.
 *  Two fixes, both kept: every colour `svg.ts` exports is now here, and `assertColours()`
 *  below refuses to write a variants file containing the literal `undefined`. */
const P = {
  ink: '#1a1224', cream: '#FFF3DE', white: '#FFFFFF',
  gold: '#F4A300', goldDark: '#B87400', mustard: '#FFC93C', mustardHi: '#FFDD6B',
  ketchup: '#D62839', tomato: '#E63946', tomatoHi: '#FF9E9E',
  lettuce: '#7CB518', lettuceHi: '#A6E24A', leafDark: '#4E8B2B',
  water: '#1E90D8', waterHi: '#5BC8F5', ice: '#8FE1FF', iceHi: '#BFF0FF',
  grape: '#7A4BC4', grapeHi: '#9B6BE0', grapeDark: '#5B2E8C', violet: '#B497D6',
  wood: '#8B4A22', woodHi: '#B4622A', meat: '#8B3A2E', meatHi: '#D98A72',
  patty: '#A05A2C', pattyDark: '#5A2E17', steel: '#DCD6E8', bone: '#F4E9DA',
  candy: '#FF6FA5', candyHi: '#FFB3D1', flame: '#FF7A2F',
};

// ── The box family, with an OVERHANGING FLAT LID ─────────────────────────────
// `ui.ts`'s `box()` draws a TRAPEZOID lid flush with the body: `M3.4 9.4 6.6 5.6 h10.8
// l3.2 3.8 z`. Two things follow at the delivered 11.83px that the 20px harness hid:
//   * a trapezoid over a rectangle is a FACETED SOLID — `boxPineapple` and `boxFire`
//     were each named "a cut gemstone" 3/3 at native size;
//   * the lid is INSIDE the body's silhouette, so the only thing saying "lid" is the
//     0.8px ink seam plus a front/lid value step that for boxBurger is 1.36.
// A lid that is WIDER than the body puts the lid in the SILHOUETTE, which is the one
// channel that survives downscaling (`food.ts`'s own rule), and no wrapped present has
// an overhanging lid. Same three colours, same emblems: colour is held fixed on purpose,
// because `a77ff30` measured three colourways at Δ = 0 of 3 with a clean twin floor.
const box2 = (front, lid, band, emblem = '') => `
<path d="M4.8 10.4h14.4v8.3a1.6 1.6 0 0 1-1.6 1.6H6.4a1.6 1.6 0 0 1-1.6-1.6z" fill="${front}"/>
<path d="M2.2 5.2h19.6v5.2H2.2z" fill="${lid}"/>
<path d="M9.9 8.4h4.2v5.2H9.9z" fill="${band}" stroke-width="1.3"/>
${emblem}`;

/* Moved down and right with the front panel, which is 1.4 units narrower than the old
   one. Nothing else about the mark changes. */
const BURGER_EMBLEM2 = `<path d="M5.8 14.1a2.6 2.6 0 0 1 5.2 0z" fill="#B4622A" stroke-width="1.2"/>
<path d="M5.6 14.1h5.6v1.5H5.6z" fill="${P.lettuce}" stroke-width="1.2"/>
<path d="M5.8 15.7h5.2a2.2 2.2 0 0 1-5.2 0z" fill="#B4622A" stroke-width="1.2"/>`;
const BOW_EMBLEM = `<path d="M12 5.6C9.2 1.6 4.8 2.8 6.2 5.6M12 5.6C14.8 1.6 19.2 2.8 17.8 5.6" fill="${P.mustard}" stroke-width="1.4"/>`;

const V = {
  _: [
    'Variants for the PAIRED plate (tools/tmp/ic_pair.mjs). GENERATED by',
    'tools/tmp/ic_mkvariants.mjs — edit that, not this.',
    '',
    'Arm [A] of every subject is SHIPPED ART: it overrides nothing, so it draws whatever',
    'src/ui/icons/ currently contains. That is what makes `--handover` possible — after a',
    'winner is pasted in, [A] and the winning arm must hash to the same pixels.',
    '',
    '`fills` is a positional substitution into the icon`s own fill= attributes.',
    '`svg` REPLACES the glyph interior, which is real new art and is why the hand-over',
    'check exists at all.',
  ],

  // ── coin — 11.03 px on rgb(253,233,212), ink outline. The primary currency. ──
  // r3: 1/3 with zoom (a bottle cap x1, a snail shell spiral x1), 0/3 without
  // (a tomato x2, an egg x1). Read off the 11x magnification of the delivered plate:
  // at 11 px the glyph is almost entirely OUTLINE. It is three separately ink-stroked
  // shapes — base ellipse, face ellipse, star — inside an 8 px circle, so 1.7 units of
  // ink (0.78 px) is drawn four times over and the gold never becomes a mass. What is
  // left is a squat two-tone oval with a dark bottom rim, which is `cap`'s construction
  // exactly (an ellipse plus a same-shape darker ellipse offset downward) and `egg`'s
  // silhouette approximately.
  // 🔴 VERDICT: [B] WON AND IS NOW SHIPPED. native 0/3 -> 3/3 (Δ +3 of 3), magnified
  // 3/3 -> 3/3, twin floor 0 of 9. [A] is therefore now the SAME ART as [B]; the pair is
  // kept so `--handover coin=B` can prove the paste by pixels, and [C] is kept because it
  // is the arm that separated "the ink budget" from "the tilt" (2/3 native: removing the
  // interior strokes recovers most of it, removing the tilt recovers all of it).
  coin: [
    { id: 'A', note: 'SHIPPED — after this pass, the disc. Before it, a tilted ellipse pair with every element ink-stroked, 0/3 native, "a bottle cap" x3.' },
    {
      id: 'B',
      note: 'DISC + RIM + un-stroked star. Kills the tilt (which is what made it a cap) and every INTERIOR stroke, so the gold is a mass and the star is at full contrast.',
      svg: `
<circle cx="12" cy="12" r="9.5" fill="${P.goldDark}"/>
<circle cx="12" cy="12" r="7.6" fill="${P.gold}" stroke="none"/>
<path d="${starPath(5, 5.8, 2.5, 12, 12)}" fill="${P.cream}" stroke="none"/>`,
    },
    {
      id: 'C',
      note: 'THE TILT KEPT, THE INTERIOR STROKES REMOVED. Isolates the two halves of the diagnosis: if C alone recovers the read, the defect was INK BUDGET; if only B does, it was the tilted silhouette.',
      svg: `
<ellipse cx="12" cy="14.2" rx="9" ry="7" fill="${P.goldDark}"/>
<ellipse cx="12" cy="11.2" rx="9" ry="7" fill="${P.gold}"/>
<path d="${starPath(5, 5.8, 2.5, 12, 11.2)}" fill="${P.cream}" stroke="none"/>`,
    },
  ],

  // ── egg — 22.72 px on WHITE. Named "a gold coin" 3/3 at native size. ────────
  // A CROSS-FAMILY leak: a weapon glyph reading as the primary currency. The cause is
  // construction, not size — the egg is a symmetric ELLIPSE whose right half is filled a
  // whole value darker, and a two-tone vertically split oval is a struck coin seen edge
  // lit. An egg is not an ellipse: it is an ovoid, narrow at the top.
  egg: [
    { id: 'A', note: 'SHIPPED — symmetric ellipse, hard vertical two-tone split.' },
    {
      id: 'B',
      note: 'TRUE OVOID (1:1.44, narrow at the top) + a bottom crescent instead of a vertical half. ⚠️ The outline is RE-STROKED after the shading, which is not decoration: the shipped icon stacks three ink-stroked paths and therefore draws its outline three times, and the first draft of this arm — which drew it once — came back visibly weaker on white. Same ink budget, deliberately.',
      svg: `
<path d="M12 3c3.6 0 6.4 5 6.4 9.8 0 4.6-2.9 8.4-6.4 8.4s-6.4-3.8-6.4-8.4c0-4.8 2.8-9.8 6.4-9.8z" fill="#E4CFA6"/>
<path d="M12 21.2c-3.5 0-6.4-3.8-6.4-8.4 0-.9.1-1.8.3-2.7.6 4.6 3.2 8 6.1 8s5.5-3.4 6.1-8c.2.9.3 1.8.3 2.7 0 4.6-2.9 8.4-6.4 8.4z" fill="#C9AE7C" stroke="none"/>
<path d="M12 3c3.6 0 6.4 5 6.4 9.8 0 4.6-2.9 8.4-6.4 8.4s-6.4-3.8-6.4-8.4c0-4.8 2.8-9.8 6.4-9.8z" fill="none"/>
<path d="M9 9.2a4 4 0 0 1 2.2-2.8" stroke="#FFFBF2" stroke-width="2.2"/>`,
    },
  ],

  // ── medal — 11.19 px on rgb(54,39,73), CREAM outline. ───────────────────────
  // A FULL MUTUAL SWAP with `trophy` at native size: trophy -> medal x3 and
  // medal -> trophy x3. Both are a gold mass with two small appendages sprouting from
  // the top, and at 11 px that is the whole reading. `ui.ts` says this icon "exists
  // purely so the trophy stops meaning two different quantities", so the swap is a
  // failure of its only job.
  medal: [
    { id: 'A', note: 'SHIPPED — two thin splayed ribbons over a gold disc with a mustard hub.' },
    {
      id: 'B',
      note: 'ONE wide ribbon with a V tail, in ketchup. The two splayed strips become one bold mass, the silhouette becomes a band-over-disc pendant, and the RED is a hue the trophy does not own at all.',
      svg: `
<path d="M8.6 1.8h6.8v7.6l-3.4 3-3.4-3z" fill="${P.ketchup}"/>
<circle cx="12" cy="15.6" r="6.3" fill="${P.gold}"/>
<circle cx="12" cy="15.6" r="3.2" fill="${P.mustardHi}" stroke="none"/>`,
    },
  ],

  // ── slow — 13.8 px on the ink fact pill, CREAM outline. ─────────────────────
  // 0/3 at native size, "a bottle cap" x3, and `cap` comes back "a snail shell spiral"
  // x2 — a real mutual swap. The cause is already written down in this repo, one file
  // over: `food.ts`'s `swirl` comment says *"a spiral drawn INSIDE a filled disc is a
  // disc, because the disc is the mass and the spiral is a scratch on it"*, and swirl
  // was redrawn for exactly that. `slow` is the same drawing and was never revisited.
  // ⚠️ A spiral RIBBON was considered and rejected on arithmetic rather than on taste:
  // at 13.8 px one viewBox unit is 0.575 px, so two turns need a gap wider than the
  // stroke and there is no pair of numbers under 24 units that gives one.
  // 🔴 VERDICT: [B] WON AND IS NOW SHIPPED. magnified 1/3 -> 3/3 (Δ +2 of 3), native
  // 0/3 -> 0/3, twin floor 0 of 9. [C] is the control that makes the finding: fattening
  // and darkening the interior spiral to near-ink, with the disc untouched, moved
  // NOTHING at either protocol — the silhouette is the whole lever.
  slow: [
    { id: 'A', note: 'SHIPPED — after this pass, the apex shell. Before it, a gold disc with an interior spiral stroke, 1/3 magnified, "a gold coin" x2.' },
    {
      id: 'B',
      note: 'APEX + a TWO-ELEMENT whorl. The silhouette is broken by a broad shell apex so it is neither a disc nor a lens, and the whorl is one 300° groove at r5 plus a centre dot — the only two marks that resolve at 0.575 px per unit. ⚠️ The first draft used two nested tones for the whorl and rendered as a plain gold teardrop: goldDark on gold under a CREAM outline has no dark edge anywhere, so the whorl was invisible. This groove is near-ink.',
      svg: `
<path d="M13 7.6 21.8 3.6 18.4 13.2z" fill="${P.gold}"/>
<circle cx="10.6" cy="14.2" r="7.8" fill="${P.gold}"/>
<path d="M14.2 18.4a5 5 0 1 1 1-5.6" stroke="#5A3200" stroke-width="2.8" fill="none" stroke-linecap="round"/>
<circle cx="10.6" cy="14.2" r="1.7" fill="#5A3200" stroke="none"/>`,
    },
    {
      id: 'C',
      note: 'WHORL CONTRAST ONLY — the shipped disc, with the interior spiral fattened and darkened to near-ink and no change to the silhouette. Isolates the two halves of the diagnosis: if C alone recovers the read the defect was CONTRAST; if only B does, `food.ts`\'s rule holds and a spiral inside a filled disc is a disc however dark you draw it.',
      svg: `
<circle cx="12" cy="12" r="9.1" fill="${P.gold}"/>
<path d="M12 12a2.9 2.9 0 1 0 2.9 2.9c0-3.4-3.2-5.3-6.3-4.1-3.4 1.3-4.6 5.3-2.6 8.2" stroke="#5A3200" stroke-width="2.8" fill="none" stroke-linecap="round"/>`,
    },
    // ── The HUE arms. 🔴 BOTH LOST, and the hypothesis behind them is FALSIFIED.
    //    [B] fixed the drawing (1/3 -> 3/3 magnified) and left the native read at 0/3,
    //    "a gold coin" x2 + "an egg" x1, from which this file inferred that a warm gold
    //    rounded mass is the currency at 13.8 px. Measured on a second plate, same
    //    silhouette, one variable, twin floor 0 of 9:
    //        A gold (shipped) 3/3 magnified, 1/3 native
    //        D brown          3/3, 1/3   Δ +0
    //        E pink           3/3, 0/3   Δ −1   ← the loudest separation made it WORSE
    //    And with the shell shipped, slow's native misreads moved to burrito / hot dog /
    //    tomato / fish — a different wrong answer every round, which is a LEGIBILITY
    //    failure rather than a collision. Kept so the next pass does not rebuild them.
    {
      id: 'D',
      note: 'SHELL BROWN. `P.woodHi`, the one warm saturated hue in the palette that no currency glyph uses, with a near-ink whorl. Warm chroma is also the budget CLAUDE.md records as SCARCE, so this spends the right one.',
      svg: `
<path d="M13 7.6 21.8 3.6 18.4 13.2z" fill="#B4622A"/>
<circle cx="10.6" cy="14.2" r="7.8" fill="#B4622A"/>
<path d="M14.2 18.4a5 5 0 1 1 1-5.6" stroke="#4A2400" stroke-width="2.8" fill="none" stroke-linecap="round"/>
<circle cx="10.6" cy="14.2" r="1.7" fill="#4A2400" stroke="none"/>`,
    },
    {
      id: 'E',
      note: 'MAXIMUM SEPARATION. `P.candy` pink — no coin, trophy, medal, gear, lock, home, cone or burst is pink, and the ink fact pill it ships on carries nothing pink either. Deliberately not a snail colour: the question this arm asks is whether HUE alone carries the native read once the silhouette is right.',
      svg: `
<path d="M13 7.6 21.8 3.6 18.4 13.2z" fill="#FF6FA5"/>
<circle cx="10.6" cy="14.2" r="7.8" fill="#FF6FA5"/>
<path d="M14.2 18.4a5 5 0 1 1 1-5.6" stroke="#8E2E56" stroke-width="2.8" fill="none" stroke-linecap="round"/>
<circle cx="10.6" cy="14.2" r="1.7" fill="#8E2E56" stroke="none"/>`,
    },
  ],

  // ── the box family — 11.83 px on white, one row of one sheet. ───────────────
  // Colour has been measured and is NOT the lever (a77ff30: three colourways, Δ = 0 of
  // 3, twin floor clean). Both arms below hold the colours FIXED and change only where
  // the lid is.
  // 🔴 [B] LOST — 1/3 -> 1/3 magnified, 0/3 -> 0/3 native, Δ +0 at both. Kept, because
  // three variables (front/lid ratio, clasp dominance, lid silhouette) have now each
  // moved with no effect and the next pass should not spend a fourth on the box's body.
  // [D] was the arm the LOSING round produced — two zoomed judges independently said the
  // box reads as a chest "because unlike the other three nothing sits ON TOP of it" —
  // and 🔴 [D] LOST TOO: 3/3 -> 3/3 magnified, 0/3 -> 0/3 native, Δ +0 at both, twin
  // floor 0 of 9. A judge's stated reason is an observation, not a lever.
  boxBurger: [
    { id: 'A', note: 'SHIPPED — trapezoid lid inside the body silhouette, burger stamped on the FRONT PANEL.' },
    { id: 'B', note: 'REJECTED (Δ +0 both protocols). OVERHANGING FLAT LID, 2.6 units wider than the body each side, trapezoid removed, clasp straddling the seam evenly.', svg: box2(P.gold, P.mustard, P.ketchup, BURGER_EMBLEM2) },
    {
      id: 'D',
      note: 'THE EMBLEM MOVES ONTO THE LID. Shipped geometry, shipped colours, one change: the burger sits ABOVE the lid and breaks the outline, which is what FLAME_EMBLEM, LEAF_EMBLEM and BOW_EMBLEM already do — and those three boxes are the ones that pass. It is the last structural asymmetry in the family.',
      svg: `
<path d="M3.4 9.4h17.2v9.4a1.7 1.7 0 0 1-1.7 1.7H5.1a1.7 1.7 0 0 1-1.7-1.7z" fill="${P.gold}"/>
<path d="M3.4 9.4 6.6 5.6h10.8l3.2 3.8z" fill="${P.mustard}"/>
<path d="M9.8 7h4.4v5.6H9.8z" fill="${P.ketchup}" stroke-width="1.3"/>
<path d="M8.9 3.9a3.1 3.1 0 0 1 6.2 0z" fill="#B4622A" stroke-width="1.2"/>
<path d="M8.7 3.9h6.6v1.1H8.7z" fill="${P.lettuce}" stroke-width="1.2"/>
<path d="M8.9 5h6.2v1.4H8.9z" fill="#B4622A" stroke-width="1.2"/>`,
    },
  ],
  boxRed: [
    { id: 'A', note: 'SHIPPED. 1/3 at native size, "a treasure chest" x2 — the other half of a mutual swap with `chest`.' },
    { id: 'B', note: 'The same overhanging lid, same colourway. Carried on the plate so the geometry is tested on TWO members of a family that shares one function, not on one.', svg: box2(P.ketchup, '#E9536A', P.mustard, BOW_EMBLEM) },
  ],

  // ── swirl — 22.72 px on WHITE, ink outline. 0/3 native, "seaweed" x3. ───────
  // The largest of this round's three sites: 1 viewBox unit is 0.947 px, so a 2-unit
  // feature really is 2 px here and this is NOT an acuity failure.
  //
  // ⚠️ ITS OWN COMMENT SAYS IT WAS ALREADY FIXED FOR THE DISC BUG — and it was. The
  // disc is gone; `food.ts` says the replacement is "two fat teardrop arms [that] make a
  // two-bladed pinwheel", and the shipped art is THREE teardrops at 0/120/240°. Read off
  // the 16x magnification of the delivered tile: each blade is a LEAF — pointed at the
  // hub, rounded at the tip, convex on both edges — and three leaves radiating from a
  // hub is a sprig. `seaweed` is a stem with three lobes of the same shape. The hue is
  // as far apart as this palette goes (P.water #1E90D8 against #3E8B4A) and three judges
  // still said seaweed, which is `slow`'s arms D/E again: hue does not carry a native
  // read. So the defect is the BLADE SHAPE and/or the radial composition, and the two
  // are separable.
  // 🔴 VERDICT: UNDECIDED, AND THE ROUND IS WHY. On the seed-13 plate the SHIPPED arm
  // scored 2/3 native — the "seaweed" x3 defect did not reproduce — so [B] (1/3, Δ −1)
  // and [C] (2/3, Δ +0) are both measured against a ceiling. In that same round `lettuce`
  // and `seaweed` swapped with each other 3/3 in BOTH directions, so the green-leaf
  // answers were occupied and were never offered to this tile. Magnified: A 2/3, B 3/3,
  // C 2/3. Kept in full — re-run on a plate where [A] reproduces 0/3; do not redraw.
  swirl: [
    { id: 'A', note: 'SHIPPED — three convex teardrop blades radiating from a cream hub. Reads as a three-leaf sprig; "seaweed" x3 native on seed 7, 2/3 on seed 13.' },
    {
      id: 'B',
      note: 'FUNNEL — a tornado: four stacked lozenges of decreasing width. The radial composition is abandoned entirely, and the silhouette (wide top tapering to a point) is owned by nothing else in the set. Rotation is carried by the STACK, which survives downscaling, rather than by a curve, which does not.',
      svg: `
<ellipse cx="12" cy="5.6" rx="9.3" ry="3.1" fill="${P.water}"/>
<ellipse cx="11.3" cy="11.4" rx="6.5" ry="2.6" fill="${P.water}"/>
<ellipse cx="10.9" cy="16.2" rx="4.1" ry="2.2" fill="${P.water}"/>
<ellipse cx="11.4" cy="20.2" rx="2.2" ry="1.7" fill="${P.water}"/>`,
    },
    {
      id: 'C',
      note: 'HOOKED BLADES, SAME RADIAL COMPOSITION. Each leaf becomes a comma whose outer edge is concave, so the outline spirals instead of radiating. Isolates the two halves of the diagnosis: if C alone recovers the read the defect was the BLADE SHAPE; if only B does, three masses around a hub is a sprig however you draw the mass.',
      svg: `
<g fill="${P.water}">
<path d="M12 12c0-5.2 2.4-8.9 6.6-9.9 1.9-.4 3.4 1.1 3 3-1 4.2-4.3 6-9.6 6.9z"/>
<path d="M12 12c0-5.2 2.4-8.9 6.6-9.9 1.9-.4 3.4 1.1 3 3-1 4.2-4.3 6-9.6 6.9z" transform="rotate(120 12 12)"/>
<path d="M12 12c0-5.2 2.4-8.9 6.6-9.9 1.9-.4 3.4 1.1 3 3-1 4.2-4.3 6-9.6 6.9z" transform="rotate(240 12 12)"/>
</g>`,
    },
  ],

  // ── heal — 13.8 px on the ink fact pill, CREAM #FFF3DE outline. ─────────────
  // 0/3 native, "a cut gemstone" x3, while `gem` itself is 3/3 — a one-way leak into a
  // shipped icon, which costs twice. `health` is the SAME heart path in ketchup and
  // scores 3/3, so the heart alone is not the defect. What differs is the cream cross:
  // on the ink pill the outline is ALSO cream, so cross and outline are one colour and
  // the green mass is cut into four pips with pale seams between them, which is `gem`'s
  // construction (a body split into panels by interior lines) exactly.
  //
  // ⚠️ A FOURTH ARM WAS BUILT, RENDERED, LOOKED AT AND DROPPED BEFORE ANY JUDGE SAW IT,
  // and it is recorded because the reason generalises: a CREAM cross grown until it
  // projects past the heart, on the ink pill, renders as a cream four-armed mark filling
  // the grid with four small green wedges behind it — i.e. as `sparkle`, which is a
  // shipped icon that is 3/3. Putting it on the plate would have spent a tile AND stolen
  // "a sparkle / twinkle" answers from the real sparkle. On this pill, cream is the
  // outline colour, so ANY cream element that becomes the dominant mass stops being a
  // mark on the glyph and becomes the glyph. That is why both surviving fix arms recolour
  // the cross first and change its size second.
  // 🔴 VERDICT: UNDECIDED, SAME REASON AS `swirl`. The SHIPPED arm scored 3/3 native on
  // the seed-13 plate — an outright ceiling — so [B] (2/3) and [C] (3/3) could not gain.
  // Magnified: all three 3/3. Across those two rounds 24 of 63 icons moved by ≥1 of 3 on
  // identical art and 13 by ≥2, `heal` among them (0/3 → 3/3). Kept in full.
  heal: [
    { id: 'A', note: 'SHIPPED — full-size heart, cream cross wholly INSIDE it, on a pill whose outline is also cream. 0/3 "a cut gemstone" x3 on seed 7, 3/3 on seed 13.' },
    {
      id: 'B',
      note: 'THE CLEFT. Same dark cross as C — colour is held FIXED across B and C — and the one variable is the top of the heart. 🔴 THE SHIPPED HEART HAS NO CLEFT: its two arcs meet at (12, 7.2) while the lobe apexes sit at y≈6.45, so the notch is 0.75 units — **0.43 px at 13.8**. A heart without a cleft is a wide-topped body ending in a point, which is `gem`. This one is cut to (12, 10.4) against apexes at y≈5.2: a 5.2-unit notch, 3.0 px, the one feature that separates the two objects at all. ⚠️ TWO earlier B arms were built and REJECTED on render, both worth recording: a CREAM cross grown to project past the heart became the mass and read as a green `sparkle` (on this pill cream is the outline colour, so a cream element that dominates stops being a mark and becomes the glyph); the same cross in #1F3D08 was dark-on-ink outside the heart and simply was not there, leaving a green mass cut into four wedges. Anything that leaves this heart must read against BOTH the green and the ink, and neither cream nor near-ink does.',
      svg: `
<path d="M12 20.6C9 17.5 3.2 14.2 3.2 10.2 3.2 6.4 6.6 4.4 9 5.4c1.6.7 2.6 2.4 3 5 .4-2.6 1.4-4.3 3-5 2.4-1 5.8 1 5.8 4.8 0 4-5.8 7.3-8.8 10.4z" fill="${P.lettuce}"/>
<path d="M12 12.4v5.2M9.4 15h5.2" stroke="#1F3D08" stroke-width="2.1"/>`,
    },
    {
      id: 'C',
      note: 'CROSS RECOLOURED, GEOMETRY UNTOUCHED — the control. The one variable is that the cross stops being the same colour as the pill\'s outline, so it is a mark ON a green mass instead of a pale seam THROUGH it. If C alone recovers the read, the defect was the cream-on-cream fragmentation and the heart\'s silhouette was never the problem; if only B does, a heart on this pill is a gemstone whatever you draw inside it.',
      svg: `
<path d="M12 20.9 4.3 13.4a4.95 4.95 0 0 1 7.7-6.2 4.95 4.95 0 0 1 7.7 6.2z" fill="${P.lettuce}"/>
<path d="M12 9.6v5.6M9.2 12.4h5.6" stroke="#1F3D08" stroke-width="2.1"/>`,
    },
  ],

  // ── timer — 13.8 px on the ink fact pill, CREAM outline. ───────────────────
  // 0/3 native, "an onion" x2 + "a lollipop" x1 — every wrong answer is a round pale
  // mass with a small thing on top, which is what the tile IS.
  //
  // 🔴 AND THE HANDS ARE NOT DRAWN IN A COLOUR. `<path d="M12 9.4v4.3h3.3"/>` sets no
  // `stroke`, so it inherits `stroke:var(--fa-ic-ink)` — the OUTLINE colour — which this
  // site flips to #FFF3DE. Cream on the #C9B8DE dial is 1.6:1 at 1.09 px. `ui.ts`'s own
  // comment reasoned about exactly this flip and guarded the DIAL fill against it
  // ("the dial is deliberately NOT cream"), then left the hands inheriting. So the clock
  // has no hands at its only delivered site and what remains is a bulb with a sprout.
  // 🔴 VERDICT: [B] WON AND IS NOW SHIPPED. native 0/3 -> 2/3 (Δ +2 of 3), magnified
  // 3/3 -> 3/3. [A] is therefore now the SAME ART as [B]; the pair is kept so
  // `--handover timer=B` can prove the paste by pixels (0% differ, max channel 0).
  // [C] is the arm that makes the finding: making the hands VISIBLE and changing nothing
  // else moved NOTHING (0/3, Δ +0). The invisibility was real and was not what the judge
  // was reacting to — `LESSONS.md` §6b.
  // ⚠️ FLOOR: that round's twins split 3 of 9, all on `chest`, its one ILLEGIBLE twin, so
  // ±1 of 3 is noise for a failing subject and only the +2 clears it.
  timer: [
    { id: 'A', note: 'SHIPPED — after this pass, the projecting ketchup hand. Before it, hands that inherited the outline colour, which is CREAM here, over a #C9B8DE dial: 1.68:1 at 1.09 px, i.e. drawn and invisible. 0/3 native, "an onion"/"a bottle cap".' },
    {
      id: 'B',
      note: 'VISIBLE HANDS + THE MINUTE HAND BREAKS THE RIM. Same hands as C, but the long hand runs out to r=11.3 and projects 3.6 units past the r=7.7 dial. The silhouette gains an asymmetric spur at 1 o\'clock — an onion and a lollipop are both symmetric about their stem, so this is the one axis on which the wrong answers cannot follow.',
      svg: `
<circle cx="12" cy="13.6" r="7.7" fill="#C9B8DE"/>
<path d="M9.5 2.4h5" stroke-width="2.1"/>
<path d="M12 2.4v3.5" stroke-width="2.1"/>
<path d="M12 13.6V8.2" stroke="${P.ketchup}" stroke-width="2.4"/>
<path d="M12 13.6 21.4 7.4" stroke="${P.ketchup}" stroke-width="2.4"/>`,
    },
    {
      id: 'C',
      note: 'HANDS MADE VISIBLE, GEOMETRY UNTOUCHED. Ketchup rather than the inherited outline colour, and 2.4 units rather than 1.9 — one concept ("the hands can be seen"), two parameters, stated. Ketchup reads on BOTH sides of this glyph: 2.7:1 against the lavender dial and 3.6:1 against the ink plate, so unlike ink or cream it cannot vanish on either. If C alone recovers the read, this was an invisible-element bug and not a silhouette one.',
      svg: `
<circle cx="12" cy="13.6" r="7.7" fill="#C9B8DE"/>
<path d="M9.5 2.4h5" stroke-width="2.1"/>
<path d="M12 2.4v3.5" stroke-width="2.1"/>
<path d="M12 9.4v4.3h3.3" stroke="${P.ketchup}" stroke-width="2.4"/>`,
    },
  ],

  // ── wrap — 22.72 px on WHITE. "a sword" x3 on BOTH reproducing panels. ──────
  // This is a ONE-WAY COLLISION with `damage`, not the legibility failure the icon's own
  // comment records. `damage` is a pale steel bar running SW→NE with a red-wrapped grip
  // at the SW end; `wrap` is a pale cream bar running SW→NE with a gold stub BEYOND its
  // NE end. Same axis, same direction, same pale-on-white value, and the gold stub is in
  // exactly the place a pommel goes. Three earlier redraws all kept the 45°.
  // The two halves of the diagnosis, separated:
  //   [C] keeps the diagonal and moves the foil from the END to a BAND ACROSS THE MIDDLE.
  //   [B] loses the diagonal entirely.
  // If C alone recovers it, the sword was the HILT; if only B does, it was the AXIS.
  wrap: [
    // 🔴 VERDICT: NEITHER SHIPPED, AND [C] IS THE ARM THAT MADE THE FINDING.
    //     A  0/3 native ("a sword" x3), 3/3 magnified
    //     C  0/3 native ("a sword" x3), 3/3 magnified   Δ +0 / +0 — the hilt is NOT the cause
    //     B  0/3 native ("an onion" x2), 0/3 magnified  Δ +0 / **-3** — the axis IS the cause,
    //        and an upright tan mass with a green ruffle on top is `onion` or `honey`.
    // The lettuce, added to break the silhouette, is what named it. Next arm: upright with
    // the outline break coming from the tortilla itself, nothing green on top.
    { id: 'A', note: 'SHIPPED — a pale cream bar at 45° with a gold stub past its upper end. "a sword" x3 on two independent native panels, and x3 again here.' },
    {
      id: 'B',
      note: 'THE DIAGONAL IS GONE. Upright, 11.6 x 16.8 (1:1.45), warm tan rather than near-white so the glyph is a MASS on white instead of an outline, an asymmetric FOLDED FLAP at the top (a capsule has two identical ends; this has a peak and a round base) and a lettuce ruffle SPILLING PAST the top edge. No axis a blade can share. ⚠️ The first cut of this arm gave it a 3.8-unit leaf; rendered, that is 3.6 px with a 1.6 px outline round it and it came back as a green dot. Widened to 8.8 units for the same reason `candy` [B] was rewidened — at 22.72 px the outline eats any element under ~6 units.',
      svg: `
<path d="M6.2 15.6V8.8L12.4 4.6l5.4 4.4v6.6a5.8 5.8 0 0 1-11.6 0z" fill="#E9B44C"/>
<path d="M6.2 8.8 12.4 4.6 17.8 9l-5.5 2.2z" fill="#CE8F2E" stroke="none"/>
<path d="M8.4 13.4c1.8 1.8 5.4 2.1 7.6.3M8 17.2c1.8 1.8 5.4 2.1 7.6.3" stroke="#CE8F2E" stroke-width="1.7"/>
<path d="M7.8 6.2c1.2-2.8 2.8-4 4.6-3.6 2 .5 3.4 1.9 4.2 4.2-3 1.2-6 1-8.8-.6z" fill="${P.lettuce}"/>`,
    },
    {
      id: 'C',
      note: 'THE DIAGONAL KEPT, THE HILT REMOVED. Byte-identical tortilla and fold marks; the same gold foil is moved from a stub past the upper end to a band ACROSS the bar at its midpoint, perpendicular to the axis. One variable: where the foil is. A blade has one thing at one end; a wrapped thing has a band round its middle.',
      svg: `
<path d="M4.4 17.6 15.6 6.4a4.4 4.4 0 0 1 3.6 3.6L8 21.2a4.4 4.4 0 0 1-3.6-3.6z" fill="#EFE0C4"/>
<path d="M8 13.1 11.1 10l4.5 4.5-3.1 3.1z" fill="#E9B44C"/>
<path d="M8.4 13.6 11.2 16.4M11.6 10.4 14.4 13.2" stroke="#CBB289" stroke-width="1.8"/>`,
    },
  ],

  // ── mustardblast — 22.72 px on WHITE. "a grilled burger patty" x3, x2. ──────
  // Both glyphs are wide two-tone horizontal lozenges. MEASURED: the sausage stadium
  // spans x 1.3..22.7 and the bun stadium x 2.9..21.1, so the sausage clears the bun by
  // **1.6 units = 1.5 px** at this size — which is one antialiased edge. `patty` is two
  // stacked flat ellipses of identical width; at 1.5 px of protrusion this is the same
  // drawing. The icon's own comment already claims the protrusion as a design feature
  // ("the sausage PROTRUDES past the bun at both ends", `chick`'s lesson) — the intent was
  // right and the number was never checked.
  mustardblast: [
    // 🔴 VERDICT: [B] WON AND IS NOW SHIPPED. native 0/3 -> 2/3 (Δ +2 of 3) against a
    // measured native floor of 1 (`boxFire`, the declared ILLEGIBLE twin, split 3 of 3);
    // magnified 2/3 -> 2/3 (Δ +0). [A] is therefore now the SAME ART as [B]; the pair is
    // kept so `--handover mustardblast=B` can prove the paste by pixels.
    { id: 'A', note: 'SHIPPED — after this pass, the narrow bun. Before it, a bun clearing the sausage by 1.6 units = 1.5 px, 0/3 native, "a grilled burger patty" x3.' },
    {
      id: 'B',
      note: 'ONE VARIABLE: THE BUN IS NARROWER. Bun stadium 2.9..21.1 -> 5.4..18.6, so the sausage clears it by 4.1 units = 3.9 px at each end. Nothing else moves — same sausage, same bun height, same zigzag, same colours. The silhouette stops being one lozenge and becomes a cylinder through a shorter cylinder.',
      svg: `
<path d="M9.7 11.4h4.6a4.3 4.3 0 0 1 0 8.6H9.7a4.3 4.3 0 0 1 0-8.6z" fill="#E8B15C"/>
<path d="M5 6.6h14a3.7 3.7 0 0 1 0 7.4H5a3.7 3.7 0 0 1 0-7.4z" fill="#C2452F"/>
<path d="M5.6 12 9 8.8 12.4 12 15.8 8.8 19.2 12" stroke="${P.mustard}" stroke-width="2.8"/>`,
    },
  ],

  // ── candy — 22.72 px on WHITE. "a double-headed arrow" = `range`. ───────────
  // Delivered ink is 17.61 x 9.09 (1.94:1) and `range`'s is 10.12 x 4.48 (2.26:1) — the
  // same proportion. The wrapper twists are QUADRILATERALS with a straight vertical outer
  // edge and straight top and bottom edges, i.e. two arrowheads, and the body between them
  // is only 1.13:1, i.e. a shaft joint. A wrapper twist is not a triangle: it PINCHES to a
  // waist at the body and then flares into a fluted fan. That waist is the one feature an
  // arrowhead cannot have — an arrowhead attaches at its widest point.
  candy: [
    // 🔴 VERDICT: NOT SHIPPED, AND THE ROUND COULD NOT ANSWER. [A] scored **3/3 native**
    // on the deciding plate, so the defect did not reproduce and [C]'s Δ is measured
    // against a ceiling the round itself supplied. [C] 3/3 native (Δ +0), 3/3 magnified
    // against [A]'s 2/3 (Δ +1). Kept for a plate where [A] reproduces 0/3.
    { id: 'A', note: 'SHIPPED — a near-circular body with two outward-pointing quadrilaterals. Straight edges, no waist. 0/3 native on two earlier panels; 3/3 on the plate that judged the tilt.' },
    // 🚨 THE BRIEFED MECHANISM — "pinch the wrapper twists concave" — WAS DRAWN TWICE AND
    // REJECTED ON RENDER, BEFORE ANY JUDGE, AND THE REASON IS ARITHMETIC RATHER THAN TASTE.
    // At 22.72 px one viewBox unit is 0.947 px and the inherited outline is 1.7 units, i.e.
    // 0.85 units of ink inset on EACH side of a path. A twist pinched to a 2.2-unit waist
    // therefore has 0.5 units of fill left at its neck; widened to 4.2 it has 2.5, and the
    // two-lobed fan beyond it is a pair of ~3-unit slivers that are eroded the same way.
    // Both cuts rendered as a DARK X with a pink dot in the middle — `close` or `sparkle`,
    // strictly worse than the arrow they were meant to fix — while the shipped straight
    // quadrilateral, which is 4.1 units wide over its whole length, still shows its pale
    // `candyHi`. Every numeric control passed on both. CLAUDE.md #3, twice in one pass.
    // **A concave pinch is not drawable in this icon system at this size.** What replaces
    // it are two changes that live where ink survives — the OUTER BOUNDARY, and the AXIS.
    {
      id: 'B',
      note: '🔴 NOT DRAWN — REJECTED ON RENDER, the third cut in a row to be. THE OUTER EDGE IS NOTCHED: the shipped quadrilateral exactly, except its straight vertical back edge becomes a V pointing INWARD, so each twist is a two-lobed fan. The reasoning was that a notch is a GAP rather than a thin fill and would therefore survive the outline where a pinch does not. It does survive — and it leaves each lobe 1.9 units thick between the notch apex (x 4.9) and the body edge (x 6.8), which the 1.7-unit outline erodes to nothing. Rendered, it is MORE star-like than the shipped arm, not less. Kept as a record so the next pass does not redraw it: at 22.72 px nothing narrower than ~5 units shows fill in this icon system, and that rules out every twist geometry that works by removing area.',
      svg: `
<ellipse cx="12" cy="12" rx="5.3" ry="4.7" fill="${P.candy}"/>
<path d="M6.8 10.1 2.7 7.2 4.9 12 2.7 16.8 6.8 13.9z" fill="${P.candyHi}"/>
<path d="M17.2 10.1 21.3 7.2 19.1 12 21.3 16.8 17.2 13.9z" fill="${P.candyHi}"/>
<path d="M9.7 10.4a3 3 0 0 1 2-1.5" stroke="${P.cream}" stroke-width="1.6"/>`,
    },
    {
      id: 'C',
      note: 'THE AXIS. Byte-identical geometry rotated -20 degrees about the centre — the same trick `cap` uses, and the exact inverse of what fixed `coin` (there a tilt CAUSED the misread; here the horizontal symmetry is what makes a body-with-two-lateral-appendages an arrow). `range` is strictly horizontal and cannot follow a tilt. One variable, and it costs no ink at all.',
      svg: `
<g transform="rotate(-20 12 12)">
<ellipse cx="12" cy="12" rx="5.3" ry="4.7" fill="${P.candy}"/>
<path d="M6.8 10.1 2.7 7.2v9.6l4.1-2.9z" fill="${P.candyHi}"/>
<path d="M17.2 10.1 21.3 7.2v9.6l-4.1-2.9z" fill="${P.candyHi}"/>
<path d="M9.7 10.4a3 3 0 0 1 2-1.5" stroke="${P.cream}" stroke-width="1.6"/>
</g>`,
    },
  ],

  // ── meat — 22.72 px on WHITE. The bone leaves the mass on ONE side only. ────
  // The brown mass is 14.5 x 16.3, i.e. a near-circle, and the only thing that is not a
  // circle about this glyph is a cream bone end at the UPPER RIGHT. A round dark mass with
  // one small pale thing off one corner has already been named "a bomb with a fuse" by two
  // judges. A bone that enters a mass has to LEAVE it: two ends, opposite corners, roughly
  // collinear through the centre, is the universal meat-on-the-bone construction and it is
  // the silhouette that stops the mass being a circle.
  meat: [
    // 🔴 VERDICT: NOT SHIPPED — INSIDE THE FLOOR, NOT DISPROVEN. [A] 0/3 native / 2/3
    // magnified; [B] 1/3 native (Δ +1) / 3/3 magnified (Δ +1). The native floor that round
    // was 1 of 3 (`boxFire` twins split on every judge), so +1 on a subject at 0/3 is noise
    // by construction. Same direction at both protocols, no loss anywhere, one variable —
    // the best-placed parked arm in this file. It wants another paired plate, not a redraw.
    { id: 'A', note: 'SHIPPED — one bone end, upper right. The rest of the silhouette is a circle. Native misreads that round were "a snail shell spiral" x2, i.e. `slow`.' },
    {
      id: 'B',
      note: 'ONE VARIABLE: A SECOND BONE END AT THE LOWER LEFT. Same knob-pair construction as the shipped one, mirrored through the mass so the two ends are roughly collinear through its centre — one bone passing behind the meat rather than one thing stuck to its corner. Mass, highlight and the existing bone are byte-identical.',
      svg: `
<path d="M2.6 12.8c0-4.6 3.4-7.6 7.6-7.6 4.3 0 6.9 2.9 6.9 6.5 0 4.9-3.4 8.7-7.6 8.7-4.1 0-6.9-3.2-6.9-7.6z" fill="${P.meat}"/>
<path d="M6.8 9.8c2.6-.8 4.5.2 5.5 2.5" stroke="${P.meatHi}" stroke-width="1.8"/>
<path d="M14.4 7.6h4.8a1.5 1.5 0 0 1 0 3h-4.8a1.5 1.5 0 0 1 0-3z" fill="${P.cream}"/>
<circle cx="19.6" cy="7.2" r="1.9" fill="${P.cream}"/>
<circle cx="19.6" cy="10.6" r="1.9" fill="${P.cream}"/>
<path d="M4.2 16.4h3.4a1.5 1.5 0 0 1 0 3H4.2a1.5 1.5 0 0 1 0-3z" fill="${P.cream}"/>
<circle cx="4" cy="16.2" r="1.9" fill="${P.cream}"/>
<circle cx="4" cy="19.6" r="1.9" fill="${P.cream}"/>`,
    },
  ],

  // ── chest — 11.03 px on a SATURATED ORANGE plate, rgb(228,91,51). ───────────
  // The smallest glyph in the set bar none, and the only one delivered on that plate. Two
  // things are measurable about it and neither has been tested:
  //  * INK BUDGET. Five separately ink-stroked shapes inside 8.6 x 8.0 delivered units.
  //    At 11.03 px one viewBox unit is 0.46 px, so the default 1.7-unit stroke is 0.78 px
  //    and it is drawn round five outlines plus a 0.85-unit keyhole (0.39 px, which cannot
  //    resolve at all). This is `coin`'s disease exactly, and `coin`'s [C] arm — interior
  //    strokes removed, silhouette untouched — recovered 2 of 3 on its own.
  //  * VALUE AGAINST THE PLATE. P.wood #8B4A22 on rgb(228,91,51) is **1.87:1**; the ink
  //    outline on the same plate is 4.94:1. So the body carries almost nothing and the
  //    glyph IS its outline — which is the worst possible arrangement for a shape whose
  //    ink budget is already spent five times over.
  // ⚠️ The PLATE is the third variable and it is NOT testable from this file set:
  // `tr-inv-empty` lives in `src/ui/screens/`. Reported, not attempted.
  chest: [
    // 🔴 VERDICT: NEITHER SHIPPED, AND BETWEEN THEM THEY RULE OUT BOTH IN-FILE VARIABLES.
    //     A  0/3 native, 3/3 magnified
    //     B  0/3 native (Δ +0), 3/3 magnified (Δ +0)   — ink budget is not the lever
    //     C  0/3 native (Δ +0), 1/3 magnified (**Δ -2**) — plate contrast is not either
    // Every native miss on all three arms was another CONTAINER, so at 11 px the domed lid
    // does not survive and this is what `box()` draws four times. 0/3 native on every arm
    // ever drawn while 3/3 magnified is `boxBurger`'s signature — a DELIVERED SIZE result.
    // The remaining variable is the PLATE, which lives in `src/ui/screens/`.
    { id: 'A', note: 'SHIPPED — five stroked shapes plus a 0.39 px keyhole; not one fill clears 2:1 against its own plate (wood 1.88, woodHi 1.24, gold 1.73; the ink outline is 5.05).' },
    {
      id: 'B',
      note: 'INK BUDGET ONLY. The gold band and the mustard clasp lose their 1.4-unit strokes and the keyhole is deleted; the body and the domed lid keep theirs, because those two ARE the silhouette and the silhouette is the only thing holding this glyph off a plate it has 1.87:1 against. Three ink outlines instead of five, one fewer shape, identical geometry and identical colours.',
      svg: `
<path d="M3.1 11.6h17.8v6.7a1.7 1.7 0 0 1-1.7 1.7H4.8a1.7 1.7 0 0 1-1.7-1.7z" fill="${P.wood}"/>
<path d="M3.1 11.6a8.9 8.9 0 0 1 17.8 0z" fill="${P.woodHi}"/>
<path d="M2.6 10.2h18.8v3H2.6z" fill="${P.gold}" stroke="none"/>
<path d="M10.3 9.8h3.4v5.4h-3.4z" fill="${P.mustard}" stroke="none"/>`,
    },
    {
      id: 'C',
      note: 'B, PLUS THE BODY VALUE. Body #8B4A22 -> #5A2E17 (1.87:1 -> 3.18:1 against the orange plate) and the dome #B4622A -> #8B4A22, so the wood stops being the same value as the plate it sits on. ⚠️ This is a VALUE move, not a desaturation — 61%->59% HSL saturation, 34%->22% lightness — because desaturating has been falsified four times here. If C beats B, the plate is the defect and the fix is not in this file set.',
      svg: `
<path d="M3.1 11.6h17.8v6.7a1.7 1.7 0 0 1-1.7 1.7H4.8a1.7 1.7 0 0 1-1.7-1.7z" fill="${P.pattyDark}"/>
<path d="M3.1 11.6a8.9 8.9 0 0 1 17.8 0z" fill="${P.wood}"/>
<path d="M2.6 10.2h18.8v3H2.6z" fill="${P.gold}" stroke="none"/>
<path d="M10.3 9.8h3.4v5.4h-3.4z" fill="${P.mustard}" stroke="none"/>`,
    },
  ],
};

/** ── THE KNOWN-BAD-INPUT GUARD FOR THIS FILE ────────────────────────────────
 *  A missing palette key interpolates to the seven characters `undefined` and produces
 *  `fill="undefined"`, which SVG discards silently: the glyph renders unfilled and every
 *  downstream control still passes, because an unfilled variant genuinely does differ
 *  from a filled one. This is the only place that can see it, so it refuses here.
 *  Shown to FAIL: deleting `water` from `P` above trips it on `swirl` [B] and [C].
 *  It also refuses an empty `svg`, which is the other way an arm can be blank. */
function assertColours(v) {
  const bad = [];
  for (const [name, arms] of Object.entries(v)) {
    if (name === '_') continue;
    for (const arm of arms) {
      const s = arm.svg ?? '';
      if (arm.svg !== undefined && !s.trim()) bad.push(`${name} [${arm.id}]: empty svg`);
      if (s.includes('undefined')) bad.push(`${name} [${arm.id}]: contains the literal "undefined" — a palette key is missing from P`);
      for (const f of s.match(/fill="[^"]*"|stroke="[^"]*"/g) ?? []) {
        const val = f.split('"')[1];
        if (!/^(#[0-9a-fA-F]{3,8}|none|currentColor|rgb|url\()/.test(val)) bad.push(`${name} [${arm.id}]: ${f} is not a colour`);
      }
    }
  }
  return bad;
}
const bad = assertColours(V);
if (bad.length) { console.error('🔴 REFUSING TO WRITE:\n  ' + bad.join('\n  ')); process.exit(1); }

writeFileSync('tools/tmp/ic_variants.json', JSON.stringify(V, null, 2) + '\n');
console.log('wrote tools/tmp/ic_variants.json');
for (const [k, v] of Object.entries(V)) {
  if (k === '_') continue;
  console.log(`  ${k.padEnd(12)} ${v.length} arms: ${v.map((x) => x.id).join(', ')}`);
}
