#!/usr/bin/env node
/**
 * X4_LAYOUT — the 2800x2000 kitchen, designed as DATA and verified before a line of
 * `kitchen.ts` is written.
 *
 * ── Why this file exists ────────────────────────────────────────────────────
 *
 * `DECISIONS §48` settles the size (x4 AREA: 1400x1000 -> 2800x2000) and gives five layout
 * rules in Uri's own words. Four of them are checkable arithmetic, and the fifth — "new
 * space needs new STRUCTURE" — is a design act. This tool owns the four:
 *
 *   1. DENSITY HELD, so ~4x area carries ~4x props (27 -> ~110), from kinds already authored.
 *   2. The HUB stays at the centre AT ITS CURRENT SCALE.
 *   3. TRUE 180-degree POINT SYMMETRY — a competitive-fairness constraint in the same
 *      category as `tools/aspect.mjs`. **Generated by transform here, never hand-typed.**
 *   5. ~4x the concealment patch COUNT at the UNCHANGED ~168 wu cap.
 *
 * ── 🔴 THE GAP RULE IS STRICTER AT THIS SIZE, AND IT IS NOT A PREFERENCE ────
 *
 * `b9bc00e` established rule 4: a gap wider than the DRAWN body (19.1 wu, Donut) and
 * narrower than the COLLIDING one (`PLAYER_SIZE` 42) is floor you can see and nothing can
 * enter. That rule survives. **A second one binds only at 2800x2000:**
 *
 *   `movement.ts:NAV_MAX_CELLS` is 40,000 and 2800x2000 at the shipped 10 wu cell needs
 *   56,000, so `navGrid` doubles the cell to **20 wu**. `NAV_CELL`'s own doc block records
 *   that cell 20 ALREADY FAILED the 1400x1000 kitchen's tightest legal gap — it cost 7 of
 *   358 cells. A corridor whose legal-centre band is narrower than ~2 cells is a corridor
 *   the flow field cannot see, so the AI walks past it.
 *
 * => **EVERY face-to-face gap is <= 18 wu (a slit) or >= 82 wu (a nav-safe corridor).**
 *    82 = `PLAYER_SIZE` (42) + 2 x the 20 wu nav cell. The 18..82 band is ILLEGAL, and it
 *    strictly contains rule 4's own 19..42 band, so one check now covers both.
 *    `movement.ts` is not this pass's file; this is the layout answer to `§52c` rather
 *    than a constant change, and it is asserted here and by `ap_reach --body-visual`.
 *
 * ── WHAT IT CHECKS, EVERY ONE PAIRED WITH A KNOWN-BAD ──────────────────────
 *   symmetry   every prop's 180-degree partner exists at the same size (generated, then
 *              re-derived from the OUTPUT so a bug in the generator cannot hide itself)
 *   overlap    no two cover boxes intersect (a mesh clip)
 *   gaps       every face-to-face gap <= 18 or >= 82, prop-to-prop and prop-to-wall
 *   nav        the real `navGrid` rule at cell 20 — all six spawns in ONE component
 *   spawns     every rule `sp_place.mjs` applies, imported from it rather than redrawn
 *   conceal    <= 168 wu across, nearest point outside the endgame keep-out, standable
 *   density    within 15% of the shipped 20.11%
 *
 * ── USE ─────────────────────────────────────────────────────────────────────
 *   node tools/tmp/x4_layout.mjs                 # the design, checked, with a report
 *   node tools/tmp/x4_layout.mjs --emit          # the kitchen.ts source blocks
 *   node tools/tmp/x4_layout.mjs --json <path>   # a dump `ap_reach --layout` can read
 *   node tools/tmp/x4_layout.mjs --selftest      # the known-bad battery
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';

const ROOT = resolve(new URL('../..', import.meta.url).pathname);
const argv = process.argv.slice(2);
const arg = (k, d = null) => { const i = argv.indexOf(`--${k}`); return i >= 0 && argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[i + 1] : (i >= 0 ? true : d); };
const has = (k) => argv.includes(`--${k}`);

// ── The size. §48, Uri: "x4 AREA, not x4 linear." ───────────────────────────
export const W = 2800;
export const H = 2000;
export const CX = W / 2, CY = H / 2;

const RULES_SRC = readFileSync(`${ROOT}/src/game/rules.ts`, 'utf8');
const num = (re, what) => { const m = re.exec(RULES_SRC); if (!m) throw new Error(`x4_layout: cannot read ${what}`); return Number(m[1].replace(/_/g, '')); };
export const PLAYER_SIZE = num(/export const PLAYER_SIZE = (\d+)/, 'PLAYER_SIZE');
const MATCH_DURATION_MS = num(/export const MATCH_DURATION_MS = ([\d_]+)/, 'MATCH_DURATION_MS');
const POT_BODY_RADIUS = num(/bodyRadius: (\d+)/, 'POT.bodyRadius');
const POT_DANGER_RADIUS = num(/dangerRadius: (\d+)/, 'POT.dangerRadius');
const POT_DAMAGE = num(/damage: (\d+)/, 'POT.damage');
const POT_TICK_MS = num(/tickMs: (\d+)/, 'POT.tickMs');
const MIN_SAFE_RADIUS = num(/export const MIN_SAFE_RADIUS = (\d+)/, 'MIN_SAFE_RADIUS');
const CONCEAL_ENDGAME_PROGRESS = num(/export const CONCEAL_ENDGAME_PROGRESS = ([\d.]+)/, 'CONCEAL_ENDGAME_PROGRESS');
const MELEE_HEAVY = num(/meleeHeavy: (\d+)/, 'REACH.meleeHeavy');
const RANGED_MAX = num(/rangedMax: (\d+)/, 'REACH.rangedMax');

/**
 * 🔴 THE LARGEST FINAL RING THIS ARENA CAN BE ASKED TO CLOSE TO — IMPORTED, NOT RE-DERIVED.
 *
 * `4bb64e4`: `MIN_SAFE_RADIUS` is no longer a constant. `sim.ts` closes the fog to
 * `minSafeRadiusFor(N)` = `max(MIN_SAFE_RADIUS, ENDGAME_STANDOFF / sin(pi/N) - POT.dangerRadius)`,
 * and at `MAX_FIGHTERS` = 6 that is **237.00 wu**, not 140. `§53a` puts six players on THIS
 * map and no other, so 237 is the number that binds here.
 *
 * ⚠️ **THE FIRST DRAFT RE-DERIVED IT AND WAS WRONG BY 1.60 wu WITHIN THE HOUR.** It read
 * `REACH.rangedMax` out of `rules.ts` and added `PLAYER_SIZE * 0.6` for the hit radius,
 * which is `HIT_RADIUS_VS_PLAYER` — but `ENDGAME_STANDOFF` takes the **max** of that and
 * `HIT_RADIUS_VS_ENEMY`, and they are not equal. It printed **235.40** against the sim's
 * **237.00**, i.e. it would have certified a layout 1.6 wu inside the real ring while
 * displaying a green tick. The sim's own function is imported instead. There is no version
 * of this file that is allowed to own a second copy of that arithmetic.
 */
const { minSafeRadiusFor } = await import(`${ROOT}/src/game/rules.ts`);
const { MAX_FIGHTERS } = await import(`${ROOT}/src/game/state.ts`);
export function finalRing(n = MAX_FIGHTERS) { return minSafeRadiusFor(n); }

/**
 * RULE 6 — NOTHING SOLID MAY STAND INSIDE THE LARGEST FINAL RING, PLUS A BODY.
 *
 * The fog's last safe circle is the only ground left at the end of a match. If a solid
 * CoverBox sits inside it, six fighters are funnelled into a ring they cannot occupy — and
 * no other gate here would say so, because the box is legal, reachable, symmetric and
 * correctly spaced from its neighbours.
 *
 * The threshold is DERIVED and it is the same one the 1400x1000 hub was placed by:
 * *"outside MIN_SAFE_RADIUS + a fighter's own reach"*, i.e. `ring + PLAYER_SIZE`. The
 * exact minimum is `ring + PLAYER_SIZE/2` — a box blocks fighter CENTRES out to its own
 * face plus a half body, so at `ring + 21` the whole ring disc is standable — and the
 * second half body is the reserve, so that the ring is not merely standable but enterable
 * and leaveable at its edge. `kitchen.ts` rule 3 is on record that a 4 wu clearance is a
 * coincidence rather than a clearance; this shipped at 4.35 and is now at 68.3.
 *
 * ⚠️ THE POT IS EXEMPT, AND THAT IS NOT A LOOPHOLE. `minSafeRadiusFor` SUBTRACTS
 * `POT.dangerRadius` in its own derivation, so the ring is already sized as an annulus
 * around the pot. Every OTHER solid box is a surprise the formula never saw.
 * ⚠️ CONCEALMENT IS EXEMPT TOO, and deliberately: a patch blocks nothing and can be shot
 * through, so a patch inside the ring is cover the endgame can actually use. The 20 shipped
 * patches are all outside it anyway — `concealmentKeepoutRadius` (496.25) is stricter.
 */
export function ringFaults(arena, margin = PLAYER_SIZE) {
  const need = finalRing() + margin;
  const out = [];
  for (const c of arena.cover) {
    if (c.kind === 'boiling_pot') continue;
    const d = Math.hypot(
      Math.max(0, Math.abs(c.x - arena.center.x) - c.w / 2),
      Math.max(0, Math.abs(c.y - arena.center.y) - c.h / 2),
    );
    if (d < need) out.push(`${c.kind}@${c.x},${c.y} nearest ${d.toFixed(2)} wu < ${need.toFixed(2)} (ring ${finalRing().toFixed(2)} + ${margin})`);
  }
  return out;
}

/** `shared.ts`'s own derivation, duplicated so this tool runs before the edit lands. */
const FOG_FIRST_CONTACT_S = 6;
export const MAX_SAFE_RADIUS = Math.round(Math.hypot(W / 2, H / 2) / (1 - (FOG_FIRST_CONTACT_S * 1000) / MATCH_DURATION_MS));

/** 🔴 The nav-cell rule. `movement.ts:navGrid` doubles the cell until the grid fits. */
export function navCellFor(width, height) {
  let cell = 10;
  while (Math.ceil(width / cell) * Math.ceil(height / cell) > 40_000) cell *= 2;
  return cell;
}
export const NAV_CELL_AT_X4 = navCellFor(W, H);
/**
 * A slit: STRICTLY BELOW the narrowest drawn body (19.1 wu, `ap_view --bodybox`) and
 * below the 18 wu floor `ap_reach --body-visual` is swept at.
 *
 * ⚠️ **16, NOT 18, AND THE 2 wu IS A MEASURED DEFECT.** A gap of exactly 18 wu against a
 * body-visual of exactly 18 leaves a MEASURE-ZERO legal line down the middle of the slit —
 * `blocked()` is a strict `<`, so the centre line is legal by 0.0 wu. `ap_reach` then
 * reported it as a real PHANTOM POCKET: 124 wu2, 60 wu long, ONE lattice cell wide, 46 wu
 * from anywhere standable. The gap was legal by the letter of the rule and produced
 * exactly the defect the rule exists to prevent, so the rule moves off its own boundary.
 */
export const GAP_SLIT_MAX = 16;
/**
 * 🔴 THE 1400x1000 REFERENCE, READ OUT OF GIT AND NOT OFF DISK.
 *
 * Every "vs the shipped map" row in this tool — the x4 area check, the 10 wu nav cell,
 * the density band, the prop count, the hub's own offsets — compares against the arena
 * that existed BEFORE this pass. `tools/arena.gameplay.json` is that file, and the
 * moment this layout is dumped into it the comparison becomes the map against itself:
 * measured, all seven of those rows flipped to FAIL with "111 -> 111" and "5600000 vs
 * 22400000" the instant the dump was refreshed. **A baseline is itself a measurement**
 * (`docs/LESSONS.md`), and a baseline that lives at a mutable path is not one.
 *
 * `0fffa1e` is the last commit whose dump is the 1400x1000 kitchen — the six-spawn pass,
 * which regenerated it — so the reference is pinned to that blob and cannot move again.
 */
let REF_1X = null;
export function ref1x() {
  if (!REF_1X) {
    const raw = execFileSync('git', ['show', '0fffa1e:tools/arena.gameplay.json'], { cwd: ROOT, encoding: 'utf8' });
    REF_1X = JSON.parse(raw);
    if (REF_1X.width !== 1400 || REF_1X.height !== 1000) {
      throw new Error(`x4_layout: the pinned 1x reference is ${REF_1X.width}x${REF_1X.height}, not 1400x1000`);
    }
  }
  return REF_1X;
}

/** A corridor: a 42 wu body plus one nav cell of slack on each side. */
export const GAP_CORRIDOR_MIN = PLAYER_SIZE + 2 * NAV_CELL_AT_X4;

// ─────────────────────────────────────────────────────────────────────────────
// THE DESIGN — the NORTH HALF only. The south half is this list under the 180
// degree point transform, generated below and never typed.
//
// Every entry is `[x, y, w, h, kind, opts?]`. `opts.build` is the literal argument
// expression `kitchen.ts` passes to its builder, so the emitted source is complete.
//
// The districts, and the lane language they extend outward from the shipped map:
//   HUB          the pot alone in a wide clearing, 4 stove islands, N/S service counters.
//                UNCHANGED offsets from CENTER — rule 2.
//   WALL SERVICE the north wall carries a service line, exactly as 1400x1000 did.
//   CORNERS      NW walk-in freezer stack / NE pantry nook — the two 1x corner idioms,
//                each now a taller cluster because there is room for one.
//   STRIPS       supply barrels FLUSH to the west and east walls (`b9bc00e` rule 4: a
//                barrel 30 wu off a wall strands floor nothing can enter).
//   GALLEYS      NEW STRUCTURE — paired counters and paired stove islands forming real
//                cook lines in the middle band, which is the space 1400x1000 never had.
//   BAYS         three open spawn bays, one per mirror pair, each with 80+ wu of runway
//                in all four cardinals.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * 🔴 THE HUB ISLAND OFFSETS, AND THEY ARE DERIVED FROM `minSafeRadiusFor(MAX_FIGHTERS)`.
 *
 * They were ±270/±200 on the 1400x1000 map, chosen so the island's INNER CORNER sat at
 * hypot(185,155) = 241 wu — *"outside MIN_SAFE_RADIUS + a fighter's own reach"*, i.e.
 * `140 + PLAYER_SIZE = 182`. That derivation is still right. **The constant it was run
 * against is not.**
 *
 * `4bb64e4` made `MIN_SAFE_RADIUS` a function of the fighter count:
 *
 *     minSafeRadiusFor(N) = max(MIN_SAFE_RADIUS, ENDGAME_STANDOFF / sin(pi/N) - POT.dangerRadius)
 *     N=2..4 -> 140.00     N=5 -> 187.42     N=6 -> **237.00**
 *
 * and `§53a` puts six players on THIS map and no other, so this is the arena that closes at
 * **237**, not at 140. At ±270/±200 the four islands sat at 241.35 — **4.35 wu inside the
 * only clearance that matters**, which is precisely the "four wu is not a clearance, it is a
 * coincidence" failure `kitchen.ts` rule 3 already records. Re-running the ORIGINAL rule
 * against the NEW constant gives 237 + 42 = 279, and ±320/±240 puts the inner corner at
 * hypot(235,195) = **305.3 wu**.
 *
 * ⚠️ THIS IS NOT A HUB THAT GREW. Every island is still 170x90, the pot is untouched, the
 * service counters have not moved, and the same expression places them — the number moved
 * because the constant under it moved. A hub PINNED at ±270 on a map that closes at 237
 * would funnel six fighters into a ring containing four solid boxes.
 */
const HUB_DX = 320, HUB_DY = 240;

/** The hub. Written relative to CENTER so "at its current scale" is literal. */
export const HUB = [
  [CX - HUB_DX, CY - HUB_DY, 170, 90, 'stove_island', { build: 'buildStoveIsland(M, w, d)' }],
  [CX + HUB_DX, CY - HUB_DY, 170, 90, 'stove_island', { build: 'buildStoveIsland(M, w, d, { panRack: true })' }],
  [CX, CY - 330, 150, 70, 'sink_counter', { yawDeg: 180, build: "buildServiceCounter(M, w, d, 'sink')" }],
];

export const NORTH = [
  // ── NW walk-in freezer stack — the 1x corner landmark, now two deep ────────
  [300, 300, 230, 190, 'freezer', { build: 'buildFreezerSized(M, w, d)' }],
  [300, 500, 230, 190, 'freezer', { build: 'buildFreezerSized(M, w, d)' }],
  [300, 650, 80, 80, 'produce_crate_tall', { build: 'buildCrateTall(M, w, d)' }],

  // ── West wall strip — barrels FLUSH (x = w/2), see `b9bc00e` rule 4 ────────
  [30, 250, 60, 50, 'supply_barrel', { build: 'buildSupplyBarrel(M, w, d)' }],
  [135, 720, 80, 80, 'produce_crate_tall', { build: 'buildCrateTall(M, w, d)' }],
  [150, 900, 90, 90, 'herb_crate', { build: 'buildHerbCrate(M, w, d)' }],

  // ── North wall service line, west run ──────────────────────────────────────
  [525, 135, 55, 55, 'stacked_pots', { build: 'buildLanePots(M, w, d)' }],
  [585, 135, 60, 50, 'supply_barrel', { build: 'buildSupplyBarrel(M, w, d)' }],
  [775, 135, 150, 70, 'sink_counter', { yawDeg: 180, build: "buildServiceCounter(M, w, d, 'sink')" }],
  [892, 135, 55, 55, 'stacked_pots', { build: 'buildLanePots(M, w, d)' }],
  [958, 135, 50, 50, 'spice_cart', { build: 'buildSpiceCart(M, w, d)' }],

  // ── North wall centrepiece ─────────────────────────────────────────────────
  [1288, 120, 60, 50, 'supply_barrel', { build: 'buildSupplyBarrel(M, w, d)' }],
  [1400, 120, 160, 55, 'prep_counter', { build: 'buildPrepCounter(M, w, d, { knifeBlock: true })' }],
  [1512, 120, 60, 50, 'supply_barrel', { build: 'buildSupplyBarrel(M, w, d, { dark: true })' }],

  // ── North wall service line, east run ──────────────────────────────────────
  [1720, 140, 90, 90, 'herb_crate', { build: 'buildHerbCrate(M, w, d)' }],
  [1815, 140, 80, 80, 'produce_crate_tall', { build: 'buildCrateTall(M, w, d)' }],
  [2015, 135, 150, 70, 'fryer_counter', { build: "buildServiceCounter(M, w, d, 'fryer')" }],
  [2120, 135, 50, 50, 'spice_cart', { build: 'buildSpiceCart(M, w, d)' }],
  [2585, 135, 90, 90, 'herb_crate', { build: 'buildHerbCrate(M, w, d)' }],
  [2720, 135, 160, 55, 'prep_counter', { build: 'buildPrepCounter(M, w, d, { rollingPin: true })' }],

  // ── NE pantry nook — crates and sacks stacked tight, the 1x idiom scaled up ─
  [2300, 250, 90, 90, 'herb_crate', { build: 'buildHerbCrate(M, w, d)' }],
  [2400, 250, 80, 80, 'produce_crate_tall', { build: 'buildCrateTall(M, w, d)' }],
  [2300, 340, 80, 80, 'produce_crate_tall', { build: 'buildCrateTall(M, w, d)' }],
  [2400, 345, 90, 90, 'herb_crate', { build: 'buildHerbCrate(M, w, d)' }],
  [2295, 425, 110, 70, 'flour_sacks', { build: 'buildFlourSack(M, w, d)' }],

  // ── East wall strip — every barrel flush, exactly as the west strip is ────
  [2770, 200, 60, 50, 'supply_barrel', { build: 'buildSupplyBarrel(M, w, d)' }],
  [2745, 520, 110, 70, 'flour_sacks', { build: 'buildFlourSack(M, w, d)' }],
  [2770, 590, 60, 50, 'supply_barrel', { build: 'buildSupplyBarrel(M, w, d, { dark: true })' }],
  [2776, 750, 48, 46, 'supply_barrel', { build: 'buildSupplyBarrel(M, w, d, { dark: true })' }],

  // ── Mid band, west: the pantry shelf and the prep galley (NEW STRUCTURE) ──
  [700, 380, 110, 70, 'flour_sacks', { build: 'buildFlourSack(M, w, d)' }],
  [700, 465, 90, 90, 'herb_crate', { build: 'buildHerbCrate(M, w, d)' }],
  [700, 650, 160, 55, 'prep_counter', { build: 'buildPrepCounter(M, w, d, { rollingPin: true })' }],
  [700, 720, 160, 55, 'prep_counter', { build: 'buildPrepCounter(M, w, d, { knifeBlock: true })' }],
  [700, 790, 55, 55, 'stacked_pots', { build: 'buildLanePots(M, w, d)' }],
  [950, 670, 90, 90, 'herb_crate', { build: 'buildHerbCrate(M, w, d)' }],
  [950, 760, 80, 80, 'produce_crate_tall', { build: 'buildCrateTall(M, w, d)' }],

  // ── Mid band, west-inner: the north lane's shoulder ────────────────────────
  [1000, 380, 90, 90, 'herb_crate', { build: 'buildHerbCrate(M, w, d)' }],
  [1000, 470, 110, 70, 'flour_sacks', { build: 'buildFlourSack(M, w, d)' }],

  // ── North hub approach — one island and a pot stack, the lane's only furniture ─
  [1400, 345, 55, 55, 'stacked_pots', { build: 'buildLanePots(M, w, d)' }],
  [1400, 430, 170, 90, 'stove_island', { build: 'buildStoveIsland(M, w, d, { panRack: true })' }],

  // ── Mid band, east-inner ───────────────────────────────────────────────────
  [1740, 380, 80, 80, 'produce_crate_tall', { build: 'buildCrateTall(M, w, d)' }],
  [1740, 460, 60, 50, 'supply_barrel', { build: 'buildSupplyBarrel(M, w, d)' }],
  [1950, 430, 160, 55, 'prep_counter', { build: 'buildPrepCounter(M, w, d, { knifeBlock: true })' }],
  [1950, 495, 55, 55, 'stacked_pots', { build: 'buildLanePots(M, w, d)' }],

  // ── Mid band, east: a cook line — two stove islands butted into one run ───
  [2100, 650, 170, 90, 'stove_island', { build: 'buildStoveIsland(M, w, d)' }],
  [2100, 745, 170, 90, 'stove_island', { build: 'buildStoveIsland(M, w, d, { panRack: true })' }],
  [2150, 900, 160, 55, 'prep_counter', { build: 'buildPrepCounter(M, w, d, { rollingPin: true })' }],
  [2262, 900, 55, 55, 'stacked_pots', { build: 'buildLanePots(M, w, d)' }],

  // ── East room — the second walk-in, anchoring the east bay's inboard wall ──
  [2450, 700, 230, 190, 'freezer', { build: 'buildFreezerSized(M, w, d)' }],
  [2450, 845, 80, 80, 'produce_crate_tall', { build: 'buildCrateTall(M, w, d)' }],

  // ── The west bay's inboard wall — what makes the bay a BAY and not a lane ──
  [450, 845, 50, 50, 'spice_cart', { build: 'buildSpiceCart(M, w, d)' }],
  [450, 910, 160, 55, 'prep_counter', { build: 'buildPrepCounter(M, w, d, { knifeBlock: true })' }],
];

/**
 * CONCEALMENT — ten patches in the north half, ten mirrors. `§48` rule 5: the AI ceiling
 * (`CONCEAL_REVEAL_RADIUS` x 2 = 168 wu) does NOT scale, so a 4x map wants 4x the COUNT.
 */
export const CONCEAL_NORTH = [
  [555, 290, 130, 'plate_stack'],
  [1070, 220, 110, 'tray_rack'],
  [700, 910, 120, 'crate_stack'],
  [1400, 235, 120, 'tray_rack'],
  [1215, 420, 120, 'plate_stack'],
  [1910, 290, 120, 'crate_stack'],
  [2650, 380, 110, 'tray_rack'],
  [2470, 975, 120, 'plate_stack'],
  [2660, 860, 110, 'crate_stack'],
  [100, 500, 110, 'tray_rack'],
];

/** Three mirror pairs, one per bay. Only the north-half seat is written; §sym mirrors it. */
export const SPAWN_NORTH = [
  { x: 300, y: 810 },   // pair A — the west bay (slots 0/1, the duel pair)
  { x: 1150, y: 210 },  // pair B — the north wall lane (slots 2/3)
  { x: 2560, y: 300 },  // pair C — the north-east corner bay (slots 4/5)
];

/** The two slow hazards. Named `puddleSouth` / `puddleNorth` in source — `arena_probe`'s
 *  extractor reads exactly those two identifiers, so the pair stays a pair. */
export const PUDDLE_SOUTH = { x: 1830, y: 1250, radius: 50 };

// ─────────────────────────────────────────────────────────────────────────────
// Assembly — the mirror is a TRANSFORM, never a typed coordinate
// ─────────────────────────────────────────────────────────────────────────────

export const mirrorPt = (p) => ({ x: W - p.x, y: H - p.y });

export function build() {
  const cover = [];
  const push = (x, y, w, h, kind, opts = {}) => cover.push({ x, y, w, h, kind, ...opts });
  for (const [x, y, w, h, kind, opts] of HUB) {
    push(x, y, w, h, kind, opts);
    // The hub's own 180-degree images. `sink_counter` mirrors to the fryer, which is what
    // 1400x1000 already shipped: identical 150x70 volumes, different dressing.
    const mk = kind === 'sink_counter' ? 'fryer_counter' : kind;
    const mb = kind === 'sink_counter' ? "buildServiceCounter(M, w, d, 'fryer')" : opts.build;
    push(W - x, H - y, w, h, mk, { ...opts, build: mb, yawDeg: kind === 'sink_counter' ? undefined : 180 });
  }
  for (const [x, y, w, h, kind, opts] of NORTH) {
    push(x, y, w, h, kind, opts);
    push(W - x, H - y, w, h, kind, { ...opts, yawDeg: opts?.yawDeg === 180 ? undefined : 180 });
  }
  // The pot is its own mirror image — the one prop a point symmetry allows to be unpaired.
  push(CX, CY, POT_BODY_RADIUS * 2, POT_BODY_RADIUS * 2, 'boiling_pot', { build: '() => pot.group' });

  const concealment = [];
  for (const [x, y, s, kind] of CONCEAL_NORTH) {
    concealment.push({ x, y, w: s, h: s, kind });
    concealment.push({ x: W - x, y: H - y, w: s, h: s, kind, yawDeg: 180 });
  }

  const spawns = [];
  for (const p of SPAWN_NORTH) { spawns.push({ ...p }); spawns.push(mirrorPt(p)); }

  const puddleNorth = { x: W - PUDDLE_SOUTH.x, y: H - PUDDLE_SOUTH.y, radius: PUDDLE_SOUTH.radius };
  const hazards = [
    { x: CX, y: CY, radius: POT_DANGER_RADIUS, kind: 'damage', damage: POT_DAMAGE, tickMs: POT_TICK_MS },
    { x: PUDDLE_SOUTH.x, y: PUDDLE_SOUTH.y, radius: PUDDLE_SOUTH.radius, kind: 'slow', slowFactor: 0.55 },
    { x: puddleNorth.x, y: puddleNorth.y, radius: puddleNorth.radius, kind: 'slow', slowFactor: 0.55 },
  ];

  return {
    id: 'kitchen', displayName: 'The Kitchen',
    width: W, height: H, center: { x: CX, y: CY }, maxSafeRadius: MAX_SAFE_RADIUS,
    playerSpawn: spawns[0], enemySpawn: spawns[1], spawns,
    cover, hazards, concealment,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// CHECKS
// ─────────────────────────────────────────────────────────────────────────────

/** Every face-to-face gap, prop-to-prop and prop-to-wall. `ap_reach.mjs:faceGaps` in
 *  structure; the thresholds are this size's, not 1400x1000's. */
export function gapFaults(arena, lo = GAP_SLIT_MAX, hi = GAP_CORRIDOR_MIN, minRun = GAP_SLIT_MAX) {
  const out = [];
  const B = arena.cover;
  const add = (a, b, axis, gap, run, at) => { if (gap > lo && gap < hi && run >= minRun) out.push({ a, b, axis, gap: +gap.toFixed(1), run: +run.toFixed(1), at }); };
  for (let i = 0; i < B.length; i++) {
    for (let j = i + 1; j < B.length; j++) {
      const A = B[i], C = B[j];
      const ovY = Math.min(A.y + A.h / 2, C.y + C.h / 2) - Math.max(A.y - A.h / 2, C.y - C.h / 2);
      const ovX = Math.min(A.x + A.w / 2, C.x + C.w / 2) - Math.max(A.x - A.w / 2, C.x - C.w / 2);
      if (ovY > 0) add(A, C, 'x', Math.abs(A.x - C.x) - (A.w + C.w) / 2, ovY, [(A.x + C.x) / 2, (A.y + C.y) / 2]);
      if (ovX > 0) add(A, C, 'y', Math.abs(A.y - C.y) - (A.h + C.h) / 2, ovX, [(A.x + C.x) / 2, (A.y + C.y) / 2]);
    }
    const A = B[i];
    add(A, { kind: 'WALL west' }, 'x', A.x - A.w / 2, A.h, [A.x - A.w / 2, A.y]);
    add(A, { kind: 'WALL east' }, 'x', arena.width - (A.x + A.w / 2), A.h, [A.x + A.w / 2, A.y]);
    add(A, { kind: 'WALL north' }, 'y', A.y - A.h / 2, A.w, [A.x, A.y - A.h / 2]);
    add(A, { kind: 'WALL south' }, 'y', arena.height - (A.y + A.h / 2), A.w, [A.x, A.y + A.h / 2]);
  }
  return out.sort((p, q) => p.gap - q.gap);
}

/** Two cover boxes that intersect are a MESH CLIP — `arena_probe --audit` exits non-zero. */
export function overlapFaults(arena) {
  const out = [];
  const B = arena.cover;
  for (let i = 0; i < B.length; i++) for (let j = i + 1; j < B.length; j++) {
    const A = B[i], C = B[j];
    if (Math.abs(A.x - C.x) < (A.w + C.w) / 2 - 1e-9 && Math.abs(A.y - C.y) < (A.h + C.h) / 2 - 1e-9) {
      out.push(`${A.kind}@${A.x},${A.y} x ${C.kind}@${C.x},${C.y}`);
    }
  }
  return out;
}

/** `ax_layout.mjs:pointSymmetryFaults`, re-derived from the OUTPUT rather than trusted. */
export function symmetryFaults(arena, tol = 1e-6) {
  const faults = [];
  for (const c of arena.cover) {
    const px = 2 * arena.center.x - c.x, py = 2 * arena.center.y - c.y;
    if (!arena.cover.some((o) => Math.abs(o.x - px) <= tol && Math.abs(o.y - py) <= tol
      && Math.abs(o.w - c.w) <= tol && Math.abs(o.h - c.h) <= tol)) {
      faults.push(`${c.kind} (${c.x},${c.y}) has no partner at (${px},${py})`);
    }
  }
  for (const c of arena.concealment ?? []) {
    const px = 2 * arena.center.x - c.x, py = 2 * arena.center.y - c.y;
    if (!arena.concealment.some((o) => Math.abs(o.x - px) <= tol && Math.abs(o.y - py) <= tol
      && Math.abs(o.w - c.w) <= tol && Math.abs(o.h - c.h) <= tol)) faults.push(`conceal ${c.kind} (${c.x},${c.y})`);
  }
  for (const s of arena.spawns) {
    const px = 2 * arena.center.x - s.x, py = 2 * arena.center.y - s.y;
    if (!arena.spawns.some((o) => Math.abs(o.x - px) <= tol && Math.abs(o.y - py) <= tol)) faults.push(`spawn (${s.x},${s.y})`);
  }
  return faults;
}

/**
 * THE NAV GRID, at `movement.ts:navGrid`'s own rule — the cell doubles until the grid
 * fits `NAV_MAX_CELLS`. Returns the component count over passable cells and whether all
 * six spawns share one. A layout whose spawns are in different nav components has an AI
 * that literally cannot path between them, and no other gate here would say so.
 */
export function navReport(arena, size = PLAYER_SIZE) {
  const cell = navCellFor(arena.width, arena.height);
  const cols = Math.ceil(arena.width / cell), rows = Math.ceil(arena.height / cell);
  const half = size / 2;
  const passable = new Uint8Array(cols * rows);
  let open = 0;
  for (let gy = 0; gy < rows; gy++) for (let gx = 0; gx < cols; gx++) {
    const cx = (gx + 0.5) * cell, cy = (gy + 0.5) * cell;
    const ok = cx >= half && cx <= arena.width - half && cy >= half && cy <= arena.height - half
      && !arena.cover.some((o) => Math.abs(cx - o.x) < (size + o.w) / 2 && Math.abs(cy - o.y) < (size + o.h) / 2);
    if (ok) { passable[gy * cols + gx] = 1; open++; }
  }
  const label = new Int32Array(cols * rows).fill(-1);
  const q = new Int32Array(cols * rows);
  let comps = 0;
  const sizes = [];
  for (let s = 0; s < cols * rows; s++) {
    if (!passable[s] || label[s] >= 0) continue;
    const id = comps++;
    let h = 0, t = 0; q[t++] = s; label[s] = id;
    while (h < t) {
      const c = q[h++], cx = c % cols, cy = (c - cx) / cols;
      for (let oy = -1; oy <= 1; oy++) for (let ox = -1; ox <= 1; ox++) {
        if (!ox && !oy) continue;
        const nx = cx + ox, ny = cy + oy;
        if (nx < 0 || nx >= cols || ny < 0 || ny >= rows) continue;
        const ni = ny * cols + nx;
        if (!passable[ni] || label[ni] >= 0) continue;
        if (ox && oy && (!passable[cy * cols + nx] || !passable[ny * cols + cx])) continue;
        label[ni] = id; q[t++] = ni;
      }
    }
    sizes.push(t);
  }
  const at = (p) => label[Math.min(rows - 1, Math.floor(p.y / cell)) * cols + Math.min(cols - 1, Math.floor(p.x / cell))];
  const spawnComps = arena.spawns.map(at);
  return { cell, cols, rows, open, comps, sizes: sizes.sort((a, b) => b - a), spawnComps, oneComponent: new Set(spawnComps).size === 1 && spawnComps[0] >= 0 };
}

/**
 * 🔴 THE DIAGONAL NOTCH — the defect `gapFaults` is structurally blind to.
 *
 * `gapFaults` only compares two boxes that overlap on one axis, which is every
 * face-to-face gap and no corner. Two props that touch only DIAGONALLY have physical
 * gaps on neither axis, and their 21 wu collision collars can still leave a channel
 * between them: measured here at 0.5 wu between the north-wall pot stack's collar and
 * the NW freezer's, which `ap_reach` then reported as a 16 wu-deep band region on a map
 * whose 1400x1000 predecessor has ZERO.
 *
 * So the test moves into INFLATED space, which is where a fighter's centre actually
 * lives: if two inflated boxes overlap on one axis, the gap on the other must be <= 0
 * (the collars merge — a solid corner) or >= 2 nav cells (a channel the flow field can
 * see). For boxes that already overlap PHYSICALLY this is exactly `gapFaults` restated,
 * so the only new answers it gives are the diagonal ones.
 */
export function notchFaults(arena, minChannel = 2 * NAV_CELL_AT_X4) {
  const out = [];
  const B = arena.cover;
  const half = PLAYER_SIZE / 2;
  for (let i = 0; i < B.length; i++) for (let j = i + 1; j < B.length; j++) {
    const A = B[i], C = B[j];
    const ovXi = Math.min(A.x + A.w / 2 + half, C.x + C.w / 2 + half) - Math.max(A.x - A.w / 2 - half, C.x - C.w / 2 - half);
    const ovYi = Math.min(A.y + A.h / 2 + half, C.y + C.h / 2 + half) - Math.max(A.y - A.h / 2 - half, C.y - C.h / 2 - half);
    if (ovXi > 0) {
      const g = Math.abs(A.y - C.y) - (A.h + C.h) / 2 - PLAYER_SIZE;
      if (g > 0 && g < minChannel) out.push(`${A.kind}@${A.x},${A.y} / ${C.kind}@${C.x},${C.y}: ${g.toFixed(1)} wu of legal-centre channel in y (needs 0 or >= ${minChannel})`);
    }
    if (ovYi > 0) {
      const g = Math.abs(A.x - C.x) - (A.w + C.w) / 2 - PLAYER_SIZE;
      if (g > 0 && g < minChannel) out.push(`${A.kind}@${A.x},${A.y} / ${C.kind}@${C.x},${C.y}: ${g.toFixed(1)} wu of legal-centre channel in x (needs 0 or >= ${minChannel})`);
    }
  }
  return out;
}

/**
 * `ap_reach.mjs`'s DEEP BAND REGION, computed here so a layout edit is checked before it
 * is written rather than after. A cell that a `visual` wu body could stand on, that a
 * `PLAYER_SIZE` body cannot reach, and that is further from reachable space than the
 * collar can possibly be. **The shipped 1400x1000 map scores ZERO**, so zero is the bar.
 */
export function deepRegions(arena, visual = 18, L = 2) {
  const cols = Math.floor(arena.width / L), rows = Math.floor(arena.height / L);
  const reach = (size, seed) => {
    const half = size / 2;
    const legal = new Uint8Array(cols * rows);
    for (let gy = 0; gy < rows; gy++) for (let gx = 0; gx < cols; gx++) {
      const x = (gx + 0.5) * L, y = (gy + 0.5) * L;
      legal[gy * cols + gx] = x >= half && x <= arena.width - half && y >= half && y <= arena.height - half
        && !arena.cover.some((o) => Math.abs(x - o.x) < (size + o.w) / 2 && Math.abs(y - o.y) < (size + o.h) / 2) ? 1 : 0;
    }
    const seen = new Uint8Array(cols * rows);
    const q = new Int32Array(cols * rows);
    let h = 0, t = 0;
    for (const s of seed) {
      const i = Math.min(rows - 1, Math.floor(s.y / L)) * cols + Math.min(cols - 1, Math.floor(s.x / L));
      if (legal[i] && !seen[i]) { seen[i] = 1; q[t++] = i; }
    }
    while (h < t) {
      const c = q[h++], cx = c % cols, cy = (c - cx) / cols;
      for (let oy = -1; oy <= 1; oy++) for (let ox = -1; ox <= 1; ox++) {
        if (!ox && !oy) continue;
        const nx = cx + ox, ny = cy + oy;
        if (nx < 0 || nx >= cols || ny < 0 || ny >= rows) continue;
        const ni = ny * cols + nx;
        if (!legal[ni] || seen[ni]) continue;
        if (ox && oy && (!legal[cy * cols + nx] || !legal[ny * cols + cx])) continue;
        seen[ni] = 1; q[t++] = ni;
      }
    }
    return { legal, seen };
  };
  const r42 = reach(PLAYER_SIZE, arena.spawns);
  const rV = reach(visual, arena.spawns);
  const band = new Uint8Array(cols * rows);
  for (let i = 0; i < band.length; i++) if (rV.seen[i] && !r42.seen[i]) band[i] = 1;
  // Chebyshev distance from the set a real fighter can reach.
  const dist = new Int32Array(cols * rows).fill(-1);
  const q = new Int32Array(cols * rows);
  let h = 0, t = 0;
  for (let i = 0; i < band.length; i++) if (r42.seen[i]) { dist[i] = 0; q[t++] = i; }
  while (h < t) {
    const c = q[h++], cx = c % cols, cy = (c - cx) / cols;
    for (let oy = -1; oy <= 1; oy++) for (let ox = -1; ox <= 1; ox++) {
      if (!ox && !oy) continue;
      const nx = cx + ox, ny = cy + oy;
      if (nx < 0 || nx >= cols || ny < 0 || ny >= rows) continue;
      const ni = ny * cols + nx;
      if (dist[ni] >= 0) continue;
      dist[ni] = dist[c] + 1; q[t++] = ni;
    }
  }
  const collarBound = (PLAYER_SIZE - visual) / 2;
  const deep = [];
  for (let gy = 0; gy < rows; gy++) for (let gx = 0; gx < cols; gx++) {
    const i = gy * cols + gx;
    if (band[i] && dist[i] * L > collarBound + L) deep.push({ x: (gx + 0.5) * L, y: (gy + 0.5) * L, depth: dist[i] * L });
  }
  return deep;
}

export function keepout(arena) {
  return Math.max(MIN_SAFE_RADIUS, arena.maxSafeRadius * (1 - CONCEAL_ENDGAME_PROGRESS));
}

export function concealFaults(arena) {
  const faults = [];
  const ceiling = MELEE_HEAVY * 2;
  const k = keepout(arena);
  for (const b of arena.concealment) {
    if (Math.max(b.w, b.h) > ceiling) faults.push(`${b.kind}@${b.x},${b.y} is ${b.w}x${b.h} — over the ${ceiling} wu AI ceiling`);
    const near = Math.hypot(Math.max(0, Math.abs(b.x - arena.center.x) - b.w / 2), Math.max(0, Math.abs(b.y - arena.center.y) - b.h / 2));
    if (near < k) faults.push(`${b.kind}@${b.x},${b.y} nearest point ${near.toFixed(1)} < keepout ${k.toFixed(2)}`);
    // Standable: sampled on the same 2 wu lattice ap_reach --selftest §G uses.
    let inside = 0, standable = 0;
    for (let x = b.x - b.w / 2 + 1; x < b.x + b.w / 2; x += 2) for (let y = b.y - b.h / 2 + 1; y < b.y + b.h / 2; y += 2) {
      inside++;
      const ok = x >= PLAYER_SIZE / 2 && x <= arena.width - PLAYER_SIZE / 2 && y >= PLAYER_SIZE / 2 && y <= arena.height - PLAYER_SIZE / 2
        && !arena.cover.some((o) => Math.abs(x - o.x) < (PLAYER_SIZE + o.w) / 2 && Math.abs(y - o.y) < (PLAYER_SIZE + o.h) / 2);
      if (ok) standable++;
    }
    if (standable / inside < 0.95) faults.push(`${b.kind}@${b.x},${b.y} only ${(standable / inside * 100).toFixed(1)}% standable`);
    if (arena.concealment.some((o) => o !== b && Math.abs(o.x - b.x) < (o.w + b.w) / 2 && Math.abs(o.y - b.y) < (o.h + b.h) / 2)) {
      faults.push(`${b.kind}@${b.x},${b.y} overlaps another patch`);
    }
  }
  return faults;
}

// ─────────────────────────────────────────────────────────────────────────────
// REPORT
// ─────────────────────────────────────────────────────────────────────────────

async function report(arena) {
  const sp = await import(`${ROOT}/tools/tmp/sp_place.mjs`);
  const density = arena.cover.reduce((s, c) => s + c.w * c.h, 0) / (arena.width * arena.height);
  const shipped = ref1x();
  const shippedDensity = shipped.cover.reduce((s, c) => s + c.w * c.h, 0) / (shipped.width * shipped.height);

  console.log(`\n== X4 LAYOUT — ${arena.width}x${arena.height}`);
  console.log(`   cover ${arena.cover.length} boxes · density ${(density * 100).toFixed(2)}% (shipped 1x: ${shipped.cover.length} / ${(shippedDensity * 100).toFixed(2)}%)`);
  console.log(`   concealment ${arena.concealment.length} patches · hazards ${arena.hazards.length} · maxSafeRadius ${arena.maxSafeRadius} · keep-out ${keepout(arena).toFixed(2)} wu`);
  console.log(`   nav cell at this size: ${NAV_CELL_AT_X4} wu  =>  legal gap band is <= ${GAP_SLIT_MAX} or >= ${GAP_CORRIDOR_MIN} wu`);
  {
    const need = finalRing() + PLAYER_SIZE;
    const solid = arena.cover.filter((c) => c.kind !== 'boiling_pot')
      .map((c) => Math.hypot(Math.max(0, Math.abs(c.x - arena.center.x) - c.w / 2), Math.max(0, Math.abs(c.y - arena.center.y) - c.h / 2)))
      .sort((p, q) => p - q);
    console.log(`   final ring at N=${MAX_FIGHTERS}: ${finalRing().toFixed(2)} wu (was a flat ${MIN_SAFE_RADIUS} before 4bb64e4) · nearest SOLID cover ${solid[0].toFixed(2)} wu`);
    console.log(`   => ${(solid[0] - finalRing()).toFixed(2)} wu of clearance, against ${PLAYER_SIZE} required and ${(PLAYER_SIZE / 2)} strictly needed`);
  }

  let bad = 0;
  const section = (name, faults, show = 8) => {
    if (faults.length === 0) { console.log(`   ok   ${name}: 0`); return; }
    bad += faults.length;
    console.log(`   FAIL ${name}: ${faults.length}`);
    for (const f of faults.slice(0, show)) console.log(`        ${typeof f === 'string' ? f : `${f.gap} wu over ${f.run} wu of run — ${f.a.kind}@${f.a.x},${f.a.y} ${f.axis === 'x' ? '|' : '—'} ${f.b.kind}${f.b.x !== undefined ? `@${f.b.x},${f.b.y}` : ''}`}`);
    if (faults.length > show) console.log(`        … ${faults.length - show} more`);
  };

  section('point-symmetry faults', symmetryFaults(arena));
  section('mesh clips (overlapping cover)', overlapFaults(arena));
  section(`illegal gaps (${GAP_SLIT_MAX} < gap < ${GAP_CORRIDOR_MIN})`, gapFaults(arena));
  section('diagonal notches (a collar channel narrower than 2 nav cells)', notchFaults(arena));
  section(`RULE 6 — solid cover inside the N=${MAX_FIGHTERS} final ring (${finalRing().toFixed(2)}) + a body`, ringFaults(arena));
  for (const v of [18, 22, 26]) {
    const d = deepRegions(arena, v);
    section(`deep band regions at body-visual ${v} (shipped 1x scores 0)`, d.map((c) => `(${c.x},${c.y}) depth ${c.depth} wu`));
  }
  section('concealment faults', concealFaults(arena));

  const nav = navReport(arena);
  console.log(`   ${nav.oneComponent ? 'ok  ' : 'FAIL'} nav grid cell ${nav.cell} wu · ${nav.cols}x${nav.rows} · ${nav.open} passable · ${nav.comps} component(s), largest ${nav.sizes[0]} · spawns in ${new Set(nav.spawnComps).size}`);
  if (!nav.oneComponent) bad++;

  console.log('\n   SPAWNS — every rule sp_place.mjs applies, imported from it:');
  let spawnBad = 0;
  for (let i = 0; i < arena.spawns.length; i++) {
    const s = arena.spawns[i];
    const v = sp.violations(s, arena);
    const c = sp.corridor(s, arena);
    const r = Math.hypot(s.x - arena.center.x, s.y - arena.center.y);
    if (v.length) spawnBad++;
    console.log(`     slot ${i}  (${String(s.x).padStart(4)},${String(s.y).padStart(4)})  worst runway ${c.worst.toFixed(1).padStart(6)} wu  r=${r.toFixed(0).padStart(4)}  ${v.length ? `FAIL ${v.join(' ')}` : 'ok'}`);
  }
  bad += spawnBad;
  const d = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
  let minSep = Infinity, minPair = null;
  for (let i = 0; i < arena.spawns.length; i++) for (let j = i + 1; j < arena.spawns.length; j++) {
    const v = d(arena.spawns[i], arena.spawns[j]);
    if (v < minSep) { minSep = v; minPair = [i, j]; }
  }
  const RANGED_MAX = num(/rangedMax: (\d+)/, 'REACH.rangedMax');
  console.log(`     min pairwise separation ${minSep.toFixed(1)} wu (slots ${minPair.join('/')}) vs REACH.rangedMax ${RANGED_MAX} — ${minSep >= RANGED_MAX ? 'CLEAR' : '🔴 A WEAPON REACHES BETWEEN TWO SPAWNS'}`);
  if (minSep < RANGED_MAX) bad++;

  const dens = Math.abs(density / shippedDensity - 1);
  console.log(`\n   density held to ${(dens * 100).toFixed(1)}% of the shipped figure — ${dens < 0.15 ? 'ok' : 'FAIL (rule 1)'}`);
  if (dens >= 0.15) bad++;

  console.log(`\n   ${bad === 0 ? '✅ EVERY CHECK PASSED' : `🔴 ${bad} FAULTS`}\n`);
  return bad;
}

// ─────────────────────────────────────────────────────────────────────────────
// EMIT — the kitchen.ts source. Written by a generator so the mirror cannot be
// hand-typed wrong, and so `arena_probe`'s source extractor still sees literal
// `addCover(...)` call sites (it cannot evaluate a loop variable).
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Section headings, keyed by the entry that opens each district. Emitted as comments so
 * the generated block reads as a MAP and not as a coordinate dump.
 */
const SECTION_NOTES = {
  '300,300': 'NW walk-in freezer stack — the 1x corner landmark, now two deep',
  '30,250': 'West wall strip — flush to the wall (x = w/2), b9bc00e rule 4',
  '525,135': 'North wall service line, west run',
  '1288,120': 'North wall centrepiece',
  '1720,140': 'North wall service line, east run',
  '2300,250': 'NE pantry nook — crates and sacks stacked tight, the 1x idiom scaled up',
  '2770,200': 'East wall strip',
  '700,380': 'Mid band west — the pantry shelf and the prep galley (NEW STRUCTURE)',
  '1000,380': "Mid band west-inner — the north lane's shoulder",
  '1400,345': 'North hub approach — one island and a pot stack, the lane\'s only furniture',
  '1740,380': 'Mid band east-inner',
  '2100,650': 'Mid band east — a cook line, two stove islands butted into one run',
  '2450,700': "East room — the second walk-in, anchoring the east bay's inboard wall",
  '450,845': "The west bay's inboard wall — what makes the bay a BAY and not a lane",
};

function emit() {
  const out = [];
  const fmt = (xE, yE, w, h, kind, yaw, build) => {
    const y = yaw !== undefined ? `, yawDeg: ${yaw}` : '';
    return `  addCover(propsGroup, cover, M, {\n`
      + `    x: ${xE}, y: ${yE}, w: ${w}, h: ${h}, kind: '${kind}'${y},\n`
      + `    build: (w, d) => ${build},\n  });`;
  };
  out.push('  // ── The central stove hub, at CENTER and at its 1400x1000 SCALE (§48 rule 2) ─');
  for (const [x, y, w, h, kind, o] of HUB) {
    const dx = x - CX, dy = y - CY;
    const ex = dx === 0 ? 'CENTER.x' : `CENTER.x ${dx < 0 ? '-' : '+'} ${Math.abs(dx)}`;
    const ey = dy === 0 ? 'CENTER.y' : `CENTER.y ${dy < 0 ? '-' : '+'} ${Math.abs(dy)}`;
    const mx = dx === 0 ? 'CENTER.x' : `CENTER.x ${dx < 0 ? '+' : '-'} ${Math.abs(dx)}`;
    const my = dy === 0 ? 'CENTER.y' : `CENTER.y ${dy < 0 ? '+' : '-'} ${Math.abs(dy)}`;
    out.push(fmt(ex, ey, w, h, kind, o.yawDeg, o.build));
    const mk = kind === 'sink_counter' ? 'fryer_counter' : kind;
    const mb = kind === 'sink_counter' ? "buildServiceCounter(M, w, d, 'fryer')" : o.build;
    out.push(fmt(mx, my, w, h, mk, kind === 'sink_counter' ? undefined : 180, mb));
  }
  for (const [x, y, w, h, kind, o] of NORTH) {
    const note = SECTION_NOTES[`${x},${y}`];
    if (note) out.push(`\n  // ── ${note} ${'─'.repeat(Math.max(3, 72 - note.length))}`);
    out.push(fmt(x, y, w, h, kind, o.yawDeg, o.build));
    out.push(fmt(`ARENA_W - ${x}`, `ARENA_H - ${y}`, w, h, kind, o.yawDeg === 180 ? undefined : 180, o.build));
  }
  return out.join('\n');
}

function emitConceal(arena) {
  const out = [];
  for (let i = 0; i < CONCEAL_NORTH.length; i++) {
    const [x, y, s, kind] = CONCEAL_NORTH[i];
    const n = i + 1;
    out.push(`  const CONCEAL_P${n}X = ${x}, CONCEAL_P${n}Y = ${y}, CONCEAL_P${n}S = ${s};`);
    out.push(`  addConceal(concealGroup, concealment, M, {\n    x: CONCEAL_P${n}X, y: CONCEAL_P${n}Y, w: CONCEAL_P${n}S, h: CONCEAL_P${n}S, kind: '${kind}',\n    build: (w, d) => buildConcealPatch(M, w, d),\n  });`);
    out.push(`  addConceal(concealGroup, concealment, M, {\n    x: ARENA_W - CONCEAL_P${n}X, y: ARENA_H - CONCEAL_P${n}Y, w: CONCEAL_P${n}S, h: CONCEAL_P${n}S,\n    kind: '${kind}', yawDeg: 180,\n    build: (w, d) => buildConcealPatch(M, w, d),\n  });`);
  }
  return out.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// SELFTEST — every row names an implementation that would FAIL it
// ─────────────────────────────────────────────────────────────────────────────
let pass = 0, fail = 0;
const check = (name, ok, detail = '') => {
  if (ok) { pass++; console.log(`  ok   - ${name}`); }
  else { fail++; console.log(`  FAIL - ${name}${detail ? `\n         ${detail}` : ''}`); }
};

async function selftest() {
  console.log(`\nx4_layout --selftest   ${W}x${H} · body ${PLAYER_SIZE} · nav cell ${NAV_CELL_AT_X4} · legal gaps <=${GAP_SLIT_MAX} or >=${GAP_CORRIDOR_MIN}\n`);
  const arena = build();

  // §A — the SIZE is x4 AREA and not x4 linear. §48's one settled number.
  console.log('§A — the size');
  const shipped = ref1x();
  check('area is exactly 4x the shipped map', (W * H) === 4 * (shipped.width * shipped.height), `${W * H} vs ${4 * shipped.width * shipped.height}`);
  check('each edge is exactly 2x', W === 2 * shipped.width && H === 2 * shipped.height);
  check('KNOWN-BAD: a x4 LINEAR map (5600x4000) is 16x the area, not 4x', (5600 * 4000) === 16 * (shipped.width * shipped.height));

  // §B — the nav-cell rule this size introduces, against movement.ts's own arithmetic.
  console.log('\n§B — the nav cell doubles at this size (§52c), and the gap band follows it');
  check('the shipped map keeps a 10 wu nav cell', navCellFor(shipped.width, shipped.height) === 10);
  check('2800x2000 forces 20 wu', NAV_CELL_AT_X4 === 20, `${NAV_CELL_AT_X4}`);
  check('the corridor minimum is PLAYER_SIZE + 2 cells', GAP_CORRIDOR_MIN === PLAYER_SIZE + 2 * NAV_CELL_AT_X4, `${GAP_CORRIDOR_MIN}`);
  check('…and it strictly contains rule 4\'s own 19..42 band', GAP_SLIT_MAX <= 19 && GAP_CORRIDOR_MIN >= PLAYER_SIZE);
  check('KNOWN-BAD: the SHIPPED 1400x1000 layout has gaps this rule would refuse',
    gapFaults({ ...shipped, cover: shipped.cover }).length > 0, `${gapFaults(shipped).length} of them — 55 wu barrel corridors and a 67.5 wu crate gap`);

  // §C — the design itself.
  console.log('\n§C — the design passes every structural check');
  check('point symmetry: 0 faults', symmetryFaults(arena).length === 0, symmetryFaults(arena).slice(0, 3).join(' · '));
  check('no mesh clips', overlapFaults(arena).length === 0, overlapFaults(arena).slice(0, 3).join(' · '));
  check(`no gap in (${GAP_SLIT_MAX}, ${GAP_CORRIDOR_MIN})`, gapFaults(arena).length === 0,
    gapFaults(arena).slice(0, 4).map((f) => `${f.gap} wu ${f.a.kind}@${f.a.x},${f.a.y}/${f.b.kind}`).join(' · '));
  check('concealment: 0 faults', concealFaults(arena).length === 0, concealFaults(arena).slice(0, 3).join(' · '));
  check('no diagonal notch — no collar channel narrower than 2 nav cells', notchFaults(arena).length === 0,
    notchFaults(arena).slice(0, 3).join(' · '));
  for (const v of [18, 22, 26]) {
    const d = deepRegions(arena, v);
    check(`ZERO deep band regions at body-visual ${v} — the shipped 1400x1000 map's own score`, d.length === 0,
      d.slice(0, 3).map((c) => `(${c.x},${c.y}) depth ${c.depth}`).join(' · '));
  }
  const nav = navReport(arena);
  check(`all six spawns share ONE nav component at cell ${nav.cell}`, nav.oneComponent, `${nav.comps} components, spawns in ${[...new Set(nav.spawnComps)].join(',')}`);

  // ── §C2 — RULE 6, the constraint `4bb64e4` created and this map is the only one it
  //          binds on (`§53a`: six players only on the x4 map).
  const solid = arena.cover.filter((c) => c.kind !== 'boiling_pot')
    .map((c) => Math.hypot(Math.max(0, Math.abs(c.x - arena.center.x) - c.w / 2), Math.max(0, Math.abs(c.y - arena.center.y) - c.h / 2)))
    .sort((p, q) => p - q);
  check(`RULE 6: no solid box inside the N=${MAX_FIGHTERS} final ring (${finalRing().toFixed(2)}) + a body`,
    ringFaults(arena).length === 0, ringFaults(arena).slice(0, 3).join(' · '));
  console.log(`         nearest solid cover ${solid[0].toFixed(2)} wu = ${(solid[0] - finalRing()).toFixed(2)} wu of clearance`);

  // §D — the symmetry check is not a tautology.
  console.log('\n§D — the guards are shown to FAIL');
  {
    const broken = JSON.parse(JSON.stringify(arena));
    broken.cover[3].x += 1;
    check('KNOWN-BAD: a 1 wu nudge of one prop breaks point symmetry', symmetryFaults(broken).length > 0, `${symmetryFaults(broken).length}`);
  }
  {
    const broken = JSON.parse(JSON.stringify(arena));
    // An AXIS mirror is a symmetric-looking SET that is not the point transform.
    broken.cover = arena.cover.filter((c) => c.y <= CY).flatMap((c) => [c, { ...c, y: H - c.y }]);
    check('KNOWN-BAD: an AXIS mirror is refused by the POINT-symmetry check', symmetryFaults(broken).length > 0, `${symmetryFaults(broken).length}`);
  }
  {
    const broken = JSON.parse(JSON.stringify(arena));
    broken.cover.push({ x: 700, y: 380 + 70 / 2 + 90 / 2 + 40, w: 110, h: 70, kind: 'probe' });
    check('KNOWN-BAD: a prop dropped 40 wu from its neighbour is caught by the gap rule',
      gapFaults(broken).length > gapFaults(arena).length, `${gapFaults(broken).length}`);
  }
  {
    // The DIAGONAL case, which `gapFaults` is structurally blind to: two boxes that
    // overlap on NEITHER axis, whose 21 wu collars leave a 3 wu channel between them.
    // This is the real defect this pass hit at the north-wall pot stack.
    const broken = JSON.parse(JSON.stringify(arena));
    broken.cover.push({ x: 480, y: 260, w: 60, h: 50, kind: 'probe_a' });
    broken.cover.push({ x: 480 + 30 + 40 + 45, y: 260 - 25 - 40 - 41, w: 80, h: 80, kind: 'probe_b' });
    const pair = (s) => s.includes('probe_a') && s.includes('probe_b');
    const seenByNotch = notchFaults(broken).filter(pair).length;
    const seenByGaps = gapFaults(broken).filter((f) => pair(`${f.a.kind}${f.b.kind}`)).length;
    check('KNOWN-BAD: two DIAGONAL props leaving a 3 wu collar channel are caught by notchFaults',
      seenByNotch > 0 && seenByGaps === 0,
      `notch sees the pair ${seenByNotch}x, gapFaults ${seenByGaps}x — gapFaults is structurally blind to it, which is the point`);
  }
  {
    // …and the same layout must produce a DEEP BAND REGION, i.e. the notch check and the
    // measurement agree about what a notch is.
    const broken = JSON.parse(JSON.stringify(arena));
    broken.cover.push({ x: 480, y: 260, w: 60, h: 50, kind: 'probe_a' });
    broken.cover.push({ x: 595, y: 154, w: 80, h: 80, kind: 'probe_b' });
    check('KNOWN-BAD: …and deepRegions() reports it as visible-but-unreachable floor',
      deepRegions(broken, 22).length > 0, `${deepRegions(broken, 22).length} cells`);
  }
  {
    const broken = JSON.parse(JSON.stringify(arena));
    // A 30 wu doorway: open to a 22 wu body, sealed to a 42 wu one — `ap_reach --selftest`
    // §C's own fixture, restated here so this tool's copy of the measurement is pinned.
    const cx = 700, cy = 500, r = 130, T = 60, gap = 30, seg = (r * 2 - gap) / 2;
    broken.cover.push(
      { x: cx - (gap / 2 + seg / 2), y: cy - r, w: seg, h: T, kind: 'wall_n_l' },
      { x: cx + (gap / 2 + seg / 2), y: cy - r, w: seg, h: T, kind: 'wall_n_r' },
      { x: cx, y: cy + r, w: r * 2 + T, h: T, kind: 'wall_s' },
      { x: cx - r, y: cy, w: T, h: r * 2 + T, kind: 'wall_w' },
      { x: cx + r, y: cy, w: T, h: r * 2 + T, kind: 'wall_e' },
    );
    check('KNOWN-BAD: a walled room with a 30 wu doorway is reported as deep band region',
      deepRegions(broken, 22).length > 0, `${deepRegions(broken, 22).length} cells`);
  }
  {
    // 🔴 THE ROW THAT WOULD HAVE CAUGHT THE SHIPPED DEFECT. The four hub islands were at
    // CENTER +-270/200 — the 1400x1000 offsets, correct against a flat `MIN_SAFE_RADIUS`
    // of 140 and **4.35 wu inside** `minSafeRadiusFor(6)` = 237. It passed every other
    // check in this file: legal, reachable, point-symmetric, correctly gapped. Restoring
    // exactly that geometry must FAIL, or rule 6 is a comment with a tick next to it.
    const broken = JSON.parse(JSON.stringify(arena));
    for (const c of broken.cover) {
      if (c.kind !== 'stove_island') continue;
      const dx = c.x - CX, dy = c.y - CY;
      if (Math.abs(dx) !== HUB_DX || Math.abs(dy) !== HUB_DY) continue;   // hub islands only
      c.x = CX + Math.sign(dx) * 270;
      c.y = CY + Math.sign(dy) * 200;
    }
    // The mid-west pair goes back with them: it moved (910,560)/(910,650) ->
    // (950,670)/(950,760) ONLY because the islands did, so reverting one and not the other
    // reconstructs a tree that never existed and the row would fail for the wrong reason.
    // It did, first time — kept as the reason this fixture is written the long way.
    for (const c of broken.cover) {
      if (c.kind === 'herb_crate' && c.x === 950 && c.y === 670) { c.x = 910; c.y = 560; }
      if (c.kind === 'herb_crate' && c.x === W - 950 && c.y === H - 670) { c.x = W - 910; c.y = H - 560; }
      if (c.kind === 'produce_crate_tall' && c.x === 950 && c.y === 760) { c.x = 910; c.y = 650; }
      if (c.kind === 'produce_crate_tall' && c.x === W - 950 && c.y === H - 760) { c.x = W - 910; c.y = H - 650; }
    }
    const f = ringFaults(broken);
    check('KNOWN-BAD: the SHIPPED ±270/±200 hub is refused — it sat 4.35 wu inside the N=6 ring',
      f.length === 4, `${f.length} faults: ${f[0] ?? ''}`);
    check('  …and that EXACT geometry passes every OTHER check here, which is why it shipped',
      gapFaults(broken).length === 0 && notchFaults(broken).length === 0
      && overlapFaults(broken).length === 0 && symmetryFaults(broken).length === 0
      && deepRegions(broken, 18).length === 0 && deepRegions(broken, 22).length === 0,
      `gaps ${gapFaults(broken).length} · notches ${notchFaults(broken).length} · clips ${overlapFaults(broken).length}`
      + ` · symmetry ${symmetryFaults(broken).length} · deep ${deepRegions(broken, 22).length}`);
    // …and the threshold is not vacuous in the other direction: a box just OUTSIDE it passes.
    const okBox = JSON.parse(JSON.stringify(arena));
    okBox.cover.push({ x: CX, y: CY + finalRing() + PLAYER_SIZE + 46, w: 90, h: 90, kind: 'probe_ok' });
    check('CONTROL: a box one wu outside the threshold is NOT refused', ringFaults(okBox).length === 0);
    const badBox = JSON.parse(JSON.stringify(arena));
    badBox.cover.push({ x: CX, y: CY + finalRing() + PLAYER_SIZE + 44, w: 90, h: 90, kind: 'probe_bad' });
    check('KNOWN-BAD: …and one wu inside it IS', ringFaults(badBox).length === 1);
  }
  {
    // The ring itself is the SIM's, imported, never re-derived here — the first draft of
    // this file re-derived it and was wrong by 1.60 wu (235.40 vs 237.00) within the hour,
    // because `ENDGAME_STANDOFF` takes the MAX of two hit radii that are not equal.
    check('the final ring is rules.ts:minSafeRadiusFor, not a second copy of its arithmetic',
      Math.abs(finalRing(6) - 237) < 1e-9 && finalRing(2) === 140,
      `N=6 ${finalRing(6).toFixed(5)} · N=2 ${finalRing(2)}`);
    check('KNOWN-BAD: the re-derivation this file used to carry is 1.60 wu SHORT',
      Math.abs((RANGED_MAX + PLAYER_SIZE * 0.6) / Math.sin(Math.PI / 6) - 95 - finalRing(6)) > 1.5,
      'a duplicated constant drifted inside one session');
  }
  {
    const broken = JSON.parse(JSON.stringify(arena));
    broken.concealment.push({ x: 700, y: 300, w: 300, h: 300, kind: 'too_big' });
    check('KNOWN-BAD: a 300 wu patch is refused by the 168 wu AI ceiling', concealFaults(broken).some((f) => f.includes('AI ceiling')));
    const b2 = JSON.parse(JSON.stringify(arena));
    b2.concealment.push({ x: CX, y: CY + 300, w: 120, h: 120, kind: 'in_keepout' });
    check('KNOWN-BAD: a patch inside the endgame keep-out is refused', concealFaults(b2).some((f) => f.includes('keepout')));
  }
  {
    // A wall through the middle must split the nav graph — proof the nav check can fail.
    const broken = JSON.parse(JSON.stringify(arena));
    for (let y = 0; y <= H; y += 100) broken.cover.push({ x: 700, y, w: 40, h: 120, kind: 'razor' });
    const n2 = navReport(broken);
    check('KNOWN-BAD: a razor wall down x=700 separates the west spawns from the rest',
      !n2.oneComponent, `${n2.comps} components, spawns in ${[...new Set(n2.spawnComps)].join(',')}`);
  }

  // §E — the spawn rules, run through sp_place.mjs itself.
  console.log('\n§E — six spawns, scored by sp_place.mjs\'s own predicates');
  {
    const sp = await import(`${ROOT}/tools/tmp/sp_place.mjs`);
    for (let i = 0; i < arena.spawns.length; i++) {
      const v = sp.violations(arena.spawns[i], arena);
      check(`slot ${i} (${arena.spawns[i].x},${arena.spawns[i].y}) clears every hard constraint`, v.length === 0, v.join(' '));
    }
    const RANGED_MAX = num(/rangedMax: (\d+)/, 'REACH.rangedMax');
    let minSep = Infinity;
    for (let i = 0; i < 6; i++) for (let j = i + 1; j < 6; j++) minSep = Math.min(minSep, Math.hypot(arena.spawns[i].x - arena.spawns[j].x, arena.spawns[i].y - arena.spawns[j].y));
    check(`every pair of seats is >= REACH.rangedMax (${RANGED_MAX}) apart`, minSep >= RANGED_MAX, `min ${minSep.toFixed(1)} wu`);
    check('KNOWN-BAD: the 1400x1000 map could only manage 75.2 wu for its third pair', 75.2 < RANGED_MAX);
  }

  // §F — density, rule 1.
  console.log('\n§F — rule 1: density held, not prop SIZE');
  {
    const d = arena.cover.reduce((s, c) => s + c.w * c.h, 0) / (W * H);
    const d0 = shipped.cover.reduce((s, c) => s + c.w * c.h, 0) / (shipped.width * shipped.height);
    check(`density within 15% of shipped (${(d * 100).toFixed(2)}% vs ${(d0 * 100).toFixed(2)}%)`, Math.abs(d / d0 - 1) < 0.15);
    check('~4x the prop COUNT', arena.cover.length >= 3 * shipped.cover.length, `${shipped.cover.length} -> ${arena.cover.length}`);
    check('every prop SIZE is drawn from the shipped set (no prop was scaled)',
      arena.cover.every((c) => shipped.cover.some((s0) => s0.w === c.w && s0.h === c.h)),
      arena.cover.filter((c) => !shipped.cover.some((s0) => s0.w === c.w && s0.h === c.h)).map((c) => `${c.kind} ${c.w}x${c.h}`).join(' '));
    check('KNOWN-BAD: a x2 linear STRETCH of the shipped layout is a quarter of the density',
      (shipped.cover.reduce((s, c) => s + c.w * c.h, 0) / (W * H)) / d0 < 0.3);
  }

  // §G — rule 2: the hub is where it was, at the size it was.
  console.log('\n§G — rule 2: the hub stays in the middle at its current scale');
  {
    const pot = arena.cover.find((c) => c.kind === 'boiling_pot');
    const sPot = shipped.cover.find((c) => c.kind === 'boiling_pot');
    check('exactly one pot, dead centre, at the shipped box size',
      arena.cover.filter((c) => c.kind === 'boiling_pot').length === 1 && pot.x === CX && pot.y === CY && pot.w === sPot.w && pot.h === sPot.h);
    check('exactly one damage hazard, dead centre, at the shipped radius',
      arena.hazards.filter((h) => h.kind === 'damage').length === 1
      && arena.hazards.find((h) => h.kind === 'damage').radius === shipped.hazards.find((h) => h.kind === 'damage').radius);
    const isl = arena.cover.filter((c) => c.kind === 'stove_island');
    const hubIsl = isl.filter((c) => Math.hypot(c.x - CX, c.y - CY) < 450);
    const sIsl = shipped.cover.filter((c) => c.kind === 'stove_island');

    // ⚠️ THIS ROW USED TO READ, AND PASSED, UNTIL 4bb64e4:
    //
    //     check('the four hub islands keep their exact offsets from CENTER and their
    //            170x90 box', hubIsl.every((c) => sIsl.some((s0) => |s0.x - c.x| == 0 ...)))
    //
    // It is kept above rather than deleted because it was the RIGHT assertion for the
    // constant it was written against and the wrong one afterwards. `MIN_SAFE_RADIUS` was
    // flat 140; ±270/±200 put the island's inner corner at 241 wu, i.e. `140 + PLAYER_SIZE`
    // with 59 wu to spare, and pinning the offsets was the honest way to say "the hub did
    // not grow". `4bb64e4` made the ring a function of N and `§53a` put six players on this
    // map, so the ring became **237** and those same offsets became **4.35 wu inside it** —
    // an assertion that actively defended the defect.
    //
    // What replaces it is what the pinned numbers were STANDING IN FOR: the island's SIZE
    // is unchanged, its placement is still a pure ±(DX,DY) about CENTER, and the offsets
    // are DERIVED from the ring rather than typed. A hub that grew with the map would fail
    // the size row; a hub pinned to the old offsets fails rule 6 in §D.
    check('the four hub islands keep their 1x SIZE — the hub did not scale with the map',
      hubIsl.length === 4 && hubIsl.every((c) => sIsl.some((s0) => s0.w === c.w && s0.h === c.h)),
      `${hubIsl.length} within 450 wu · ${[...new Set(hubIsl.map((c) => `${c.w}x${c.h}`))].join(' ')}`);
    check('…and their placement is still a pure ±(DX,DY) about CENTER',
      hubIsl.length === 4 && hubIsl.every((c) => Math.abs(Math.abs(c.x - CX) - HUB_DX) < 1e-9
        && Math.abs(Math.abs(c.y - CY) - HUB_DY) < 1e-9)
      && new Set(hubIsl.map((c) => `${Math.sign(c.x - CX)},${Math.sign(c.y - CY)}`)).size === 4,
      `±${HUB_DX}/±${HUB_DY}`);
    check('…and DX/DY are DERIVED: the inner corner clears the N=6 ring by a body',
      Math.hypot(HUB_DX - 85, HUB_DY - 45) >= finalRing() + PLAYER_SIZE,
      `inner corner ${Math.hypot(HUB_DX - 85, HUB_DY - 45).toFixed(2)} wu vs ${(finalRing() + PLAYER_SIZE).toFixed(2)} needed`);
    check('KNOWN-BAD: a hub SCALED with the map would put an island 540 wu out, not 320',
      HUB_DX < 540 && HUB_DX > 270,
      `${HUB_DX} — bigger than the 1x 270 because the RING moved, not because the map did`);
  }

  // §H — rule 5: the concealment CEILING did not scale, so the COUNT did.
  console.log('\n§H — rule 5: 4x the patch COUNT at the unchanged 168 wu cap');
  {
    check(`${arena.concealment.length} patches, ~4x the shipped 6`, arena.concealment.length >= 18 && arena.concealment.length <= 24, `${arena.concealment.length}`);
    check('every patch is still <= the 168 wu AI ceiling', arena.concealment.every((b) => Math.max(b.w, b.h) <= MELEE_HEAVY * 2));
    check('the ceiling did NOT scale with the arena', MELEE_HEAVY * 2 === 168);
  }

  console.log(`\n${fail === 0 ? 'PASS' : 'FAIL'}  ${pass} passed, ${fail} failed\n`);
  process.exitCode = fail ? 1 : 0;
}

// ── main ────────────────────────────────────────────────────────────────────
const IS_MAIN = process.argv[1] && resolve(process.argv[1]) === resolve(new URL(import.meta.url).pathname);
if (IS_MAIN) {
  if (has('selftest')) {
    await selftest();
  } else if (arg('json')) {
    const arena = build();
    const p = resolve(String(arg('json')));
    mkdirSync(dirname(p), { recursive: true });
    // Strip the source-only `build` strings: a dump is data.
    const clean = { ...arena, cover: arena.cover.map(({ build: _b, ...c }) => c) };
    writeFileSync(p, `${JSON.stringify(clean, null, 2)}\n`);
    console.log(p);
  } else if (has('emit')) {
    const arena = build();
    console.log('// ── COVER ───────────────────────────────────────────────────────────────');
    console.log(emit());
    console.log('\n// ── CONCEALMENT ─────────────────────────────────────────────────────────');
    console.log(emitConceal(arena));
  } else {
    const bad = await report(build());
    process.exitCode = bad ? 1 : 0;
  }
}
